import { validateAccountKeyAlignment } from "../broker/authoritativeAccountKey";
import { OWNER_ACCOUNT_KEY } from "../broker/ownerAccountKey";

/**
 * envCheck.ts — Single-source startup environment validator.
 *
 * Checks every variable the Paper Desk system requires and returns a
 * structured report with PASS / WARNING / FAIL per item plus human-readable
 * remediation steps.  Safe to import server-side only (never in browser bundles).
 *
 * Variables audited
 * ─────────────────
 *  AUTH_JWT_SECRET        — signs / verifies the raig_session JWT cookie
 *  ADMIN_USERNAME         — login username
 *  ADMIN_PASSWORD_HASH    — scrypt hash produced by generate-password-hash.mjs
 *  MONGODB_URI            — Atlas connection string
 *  MONGODB_DB             — Atlas database name (default loop_trades)
 *  OWNER_ACCOUNT_KEY      — hardcoded in ownerAuth.ts; engine reads from env
 *  INTERNAL_API_URL       — Vercel → Go engine base URL
 */

export type CheckStatus = "PASS" | "WARNING" | "FAIL";

export type EnvCheckResult = {
  key: string;
  status: CheckStatus;
  value_hint: string;   // safe display: masked / "set" / "missing"
  message: string;
  fix: string;
};

export type EnvReport = {
  ok: boolean;           // true only when every item is PASS or WARNING
  ready_for_login: boolean;  // AUTH_JWT_SECRET + ADMIN_* all set
  ready_for_mongo: boolean;  // MONGODB_URI set and looks valid
  ready_for_engine: boolean; // INTERNAL_API_URL set
  account_key: string;       // effective account key
  checks: EnvCheckResult[];
  checked_at: string;
};

// ── Individual checkers ──────────────────────────────────────────────────────

function checkAuthJwtSecret(): EnvCheckResult {
  const v = process.env.AUTH_JWT_SECRET?.trim() ?? "";
  if (!v) {
    return {
      key: "AUTH_JWT_SECRET",
      status: "FAIL",
      value_hint: "missing",
      message: "Not set — every Paper Desk API returns 503 and login throws 500.",
      fix: 'Generate: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))" then add AUTH_JWT_SECRET=<value> to .env.local AND Vercel env vars.',
    };
  }
  if (v.length < 32) {
    return {
      key: "AUTH_JWT_SECRET",
      status: "WARNING",
      value_hint: `set (${v.length} chars — too short)`,
      message: "Secret is shorter than 32 characters. Brute-force risk.",
      fix: "Replace with a 64-character hex string: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"",
    };
  }
  return {
    key: "AUTH_JWT_SECRET",
    status: "PASS",
    value_hint: `set (${v.length} chars)`,
    message: "JWT secret is configured.",
    fix: "",
  };
}

function checkAdminUsername(): EnvCheckResult {
  const v = process.env.ADMIN_USERNAME?.trim() ?? "";
  if (!v) {
    return {
      key: "ADMIN_USERNAME",
      status: "FAIL",
      value_hint: "missing",
      message: "Not set — /api/auth/login returns 503.",
      fix: "Add ADMIN_USERNAME=<your_username> to .env.local AND Vercel env vars.",
    };
  }
  return {
    key: "ADMIN_USERNAME",
    status: "PASS",
    value_hint: `set ("${v}")`,
    message: "Admin username configured.",
    fix: "",
  };
}

function checkAdminPasswordHash(): EnvCheckResult {
  const v = process.env.ADMIN_PASSWORD_HASH?.trim() ?? "";
  if (!v) {
    return {
      key: "ADMIN_PASSWORD_HASH",
      status: "FAIL",
      value_hint: "missing",
      message: "Not set — /api/auth/login returns 503.",
      fix: "Run: node client/scripts/generate-password-hash.mjs <password>  then add ADMIN_PASSWORD_HASH=scrypt:... to .env.local AND Vercel env vars.",
    };
  }
  if (!v.startsWith("scrypt:")) {
    return {
      key: "ADMIN_PASSWORD_HASH",
      status: "FAIL",
      value_hint: "set (wrong format)",
      message: "Hash does not start with 'scrypt:' — it was not generated by generate-password-hash.mjs.",
      fix: "Re-generate: node client/scripts/generate-password-hash.mjs <password>",
    };
  }
  const parts = v.split(":");
  if (parts.length !== 3) {
    return {
      key: "ADMIN_PASSWORD_HASH",
      status: "FAIL",
      value_hint: "set (malformed)",
      message: "Hash format is 'scrypt:<salt>:<key>' — wrong number of segments.",
      fix: "Re-generate: node client/scripts/generate-password-hash.mjs <password>",
    };
  }
  return {
    key: "ADMIN_PASSWORD_HASH",
    status: "PASS",
    value_hint: "set (scrypt hash)",
    message: "Password hash correctly formatted.",
    fix: "",
  };
}

function checkMongoUri(): EnvCheckResult {
  const v = process.env.MONGODB_URI?.trim() ?? "";
  if (!v) {
    return {
      key: "MONGODB_URI",
      status: "FAIL",
      value_hint: "missing",
      message: "Not set — all Paper Desk routes return 503.",
      fix: "Add MONGODB_URI=mongodb+srv://... to .env.local AND Vercel env vars. Get URI from MongoDB Atlas → Connect → Drivers → Node.js.",
    };
  }
  if (!v.startsWith("mongodb+srv://") && !v.startsWith("mongodb://")) {
    return {
      key: "MONGODB_URI",
      status: "FAIL",
      value_hint: "set (wrong scheme)",
      message: "URI must start with mongodb+srv:// or mongodb://.",
      fix: "Correct the URI in .env.local and Vercel.",
    };
  }
  // Mask credentials for the hint
  const masked = v.replace(/:\/\/([^@]+)@/, "://<redacted>@");
  return {
    key: "MONGODB_URI",
    status: "PASS",
    value_hint: masked,
    message: "MongoDB URI is configured.",
    fix: "",
  };
}

function checkMongoDb(): EnvCheckResult {
  const v =
    process.env.MONGODB_DB_NAME?.trim() ||
    process.env.MONGODB_DB?.trim() ||
    "";
  const effective = v || "loop_trades";
  const isDefault = !v;
  return {
    key: "MONGODB_DB / MONGODB_DB_NAME",
    status: isDefault ? "WARNING" : "PASS",
    value_hint: isDefault ? `not set (defaulting to "${effective}")` : `set ("${effective}")`,
    message: isDefault
      ? `No MONGODB_DB set — using default "${effective}". Explicit is better.`
      : `Database "${effective}" configured.`,
    fix: isDefault ? 'Add MONGODB_DB=loop_trades to .env.local to make this explicit.' : "",
  };
}

function checkDeskWorkerAccountKey(): EnvCheckResult {
  const legacy = process.env.DESK_WORKER_ACCOUNT_KEY?.trim() ?? "";
  const validation = validateAccountKeyAlignment();

  if (legacy.startsWith("anon_")) {
    return {
      key: "DESK_WORKER_ACCOUNT_KEY",
      status: "FAIL",
      value_hint: `"${legacy}"`,
      message: `Retired anonymous key "${legacy}" — remove from Vercel/VPS env.`,
      fix: `Unset DESK_WORKER_ACCOUNT_KEY or set OWNER_ACCOUNT_KEY=mock_trading_default everywhere.`,
    };
  }

  if (!validation.ok) {
    return {
      key: "ACCOUNT_KEY_ALIGNMENT",
      status: "FAIL",
      value_hint: legacy || "(unset)",
      message: validation.errors.join("; "),
      fix: "Align OWNER_ACCOUNT_KEY and remove anon_* keys. See authoritativeAccountKey.ts.",
    };
  }

  if (legacy && legacy !== validation.accountKey) {
    return {
      key: "DESK_WORKER_ACCOUNT_KEY",
      status: "WARNING",
      value_hint: `"${legacy}" (ignored)`,
      message: `Deprecated env var set — all paths use "${validation.accountKey}".`,
      fix: "Remove DESK_WORKER_ACCOUNT_KEY from Vercel and VPS .env.",
    };
  }

  return {
    key: "ACCOUNT_KEY_ALIGNMENT",
    status: "PASS",
    value_hint: validation.accountKey,
    message: `All subsystems use authoritative account key "${validation.accountKey}".`,
    fix: "",
  };
}

function checkOwnerAccountKey(): EnvCheckResult {
  const v = process.env.OWNER_ACCOUNT_KEY?.trim() ?? "";
  const effective = v || OWNER_ACCOUNT_KEY;
  if (v && v !== OWNER_ACCOUNT_KEY) {
    return {
      key: "OWNER_ACCOUNT_KEY",
      status: "FAIL",
      value_hint: `"${effective}"`,
      message: `Custom account key "${effective}" must match frontend constant "${OWNER_ACCOUNT_KEY}".`,
      fix: `Remove OWNER_ACCOUNT_KEY env var or set it to "${OWNER_ACCOUNT_KEY}".`,
    };
  }
  return {
    key: "OWNER_ACCOUNT_KEY",
    status: "PASS",
    value_hint: `effective: "${effective}"`,
    message: v
      ? `Explicitly set to "${effective}" — matches frontend constant.`
      : `Not set — using default "${OWNER_ACCOUNT_KEY}" which matches frontend constant.`,
    fix: "",
  };
}

function checkInternalApiUrl(): EnvCheckResult {
  const v = process.env.INTERNAL_API_URL?.trim() ?? "";
  if (!v) {
    return {
      key: "INTERNAL_API_URL",
      status: "WARNING",
      value_hint: "not set (defaulting to http://localhost:8080)",
      message: "Not set — engine proxy falls back to http://localhost:8080. Works locally; fatal on Vercel production.",
      fix: "Add INTERNAL_API_URL=https://<lightsail-ip>:8080 to Vercel env vars.",
    };
  }
  return {
    key: "INTERNAL_API_URL",
    status: "PASS",
    value_hint: v,
    message: "Engine URL configured.",
    fix: "",
  };
}

// ── Main export ──────────────────────────────────────────────────────────────

/**
 * Run all environment checks and return a structured report.
 * Call server-side only (e.g., in API routes, not in browser components).
 */
export function runEnvChecks(): EnvReport {
  const checks: EnvCheckResult[] = [
    checkAuthJwtSecret(),
    checkAdminUsername(),
    checkAdminPasswordHash(),
    checkMongoUri(),
    checkMongoDb(),
    checkOwnerAccountKey(),
    checkDeskWorkerAccountKey(),
    checkInternalApiUrl(),
  ];

  const fails = checks.filter((c) => c.status === "FAIL");
  const ok = fails.length === 0;

  const authChecks = checks.filter((c) =>
    ["AUTH_JWT_SECRET", "ADMIN_USERNAME", "ADMIN_PASSWORD_HASH"].includes(c.key),
  );
  const ready_for_login = authChecks.every((c) => c.status === "PASS");

  const mongoCheck = checks.find((c) => c.key === "MONGODB_URI");
  const ready_for_mongo = mongoCheck?.status === "PASS";

  const engineCheck = checks.find((c) => c.key === "INTERNAL_API_URL");
  const ready_for_engine = engineCheck?.status === "PASS";

  const account_key = validateAccountKeyAlignment().accountKey;

  return {
    ok,
    ready_for_login,
    ready_for_mongo,
    ready_for_engine,
    account_key,
    checks,
    checked_at: new Date().toISOString(),
  };
}

/**
 * Log a human-readable startup report to the console.
 * Call once at Next.js server startup (e.g., in instrumentation.ts).
 */
export function logEnvReport(): void {
  const r = runEnvChecks();
  const sep = "═".repeat(62);
  console.log(`\n${sep}`);
  console.log("  RAIG Paper Desk — Environment Startup Report");
  console.log(sep);
  for (const c of r.checks) {
    const icon = c.status === "PASS" ? "✅" : c.status === "WARNING" ? "⚠️ " : "❌";
    console.log(`  ${icon} ${c.key.padEnd(32)} ${c.status}  ${c.value_hint}`);
    if (c.status !== "PASS") {
      console.log(`       Problem : ${c.message}`);
      console.log(`       Fix     : ${c.fix}`);
    }
  }
  console.log(sep);
  console.log(`  ready_for_login  : ${r.ready_for_login}`);
  console.log(`  ready_for_mongo  : ${r.ready_for_mongo}`);
  console.log(`  ready_for_engine : ${r.ready_for_engine}`);
  console.log(`  account_key      : ${r.account_key}`);
  if (!r.ok) {
    console.log("");
    console.log("  ⛔  BLOCKERS DETECTED — Paper Desk will not function correctly.");
    console.log("      Apply the fixes above and restart.");
  } else {
    console.log("");
    console.log("  ✅  All checks passed — Paper Desk is ready.");
  }
  console.log(`${sep}\n`);
}
