package sor

import (
	"fmt"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Metrics holds all Prometheus collectors for the SOR subsystem.
type Metrics struct {
	RoutingLatency   prometheus.Histogram
	ExecutionLatency prometheus.Histogram
	VenueHealth      *prometheus.GaugeVec   // labels: venue
	SlippageBps      *prometheus.HistogramVec // labels: venue
	FillRate         *prometheus.GaugeVec   // labels: venue
	CostSavingsBps   prometheus.Gauge
	FailoverTotal    *prometheus.CounterVec // labels: from_venue, to_venue
	LiquidityScore   *prometheus.GaugeVec   // labels: venue, symbol
	RoutesTotal      *prometheus.CounterVec // labels: winning_venue, algo
	RejectionsTotal  *prometheus.CounterVec // labels: venue
	VenueSelections  *prometheus.CounterVec // labels: venue
	ChildOrdersTotal prometheus.Counter
}

// NewMetrics registers all SOR Prometheus metrics.
func NewMetrics() *Metrics {
	return &Metrics{
		RoutingLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Namespace: "sor",
			Name:      "routing_latency_seconds",
			Help:      "Latency of the SOR routing decision (selection + planning).",
			Buckets:   []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5},
		}),
		ExecutionLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Namespace: "sor",
			Name:      "execution_latency_seconds",
			Help:      "End-to-end execution latency from route to all child fills.",
			Buckets:   []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 30},
		}),
		VenueHealth: promauto.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: "sor",
			Name:      "venue_health_score",
			Help:      "Per-venue health score (0-100).",
		}, []string{"venue"}),
		SlippageBps: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: "sor",
			Name:      "slippage_bps",
			Help:      "Realized slippage in basis points per venue.",
			Buckets:   []float64{0, 1, 2, 5, 10, 20, 50, 100},
		}, []string{"venue"}),
		FillRate: promauto.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: "sor",
			Name:      "venue_fill_rate",
			Help:      "Per-venue fill rate (0-1).",
		}, []string{"venue"}),
		CostSavingsBps: promauto.NewGauge(prometheus.GaugeOpts{
			Namespace: "sor",
			Name:      "cost_savings_bps",
			Help:      "Estimated routing cost savings vs naive single-venue execution (bps).",
		}),
		FailoverTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Namespace: "sor",
			Name:      "failover_total",
			Help:      "Total venue failover events.",
		}, []string{"from_venue", "to_venue"}),
		LiquidityScore: promauto.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: "sor",
			Name:      "liquidity_score",
			Help:      "Executable-liquidity score (0-1) per venue/symbol.",
		}, []string{"venue", "symbol"}),
		RoutesTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Namespace: "sor",
			Name:      "routes_total",
			Help:      "Total parent orders routed, by winning venue and algo.",
		}, []string{"winning_venue", "algo"}),
		RejectionsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Namespace: "sor",
			Name:      "rejections_total",
			Help:      "Total child-order rejections per venue.",
		}, []string{"venue"}),
		VenueSelections: promauto.NewCounterVec(prometheus.CounterOpts{
			Namespace: "sor",
			Name:      "venue_selections_total",
			Help:      "Total times each venue was selected for routing.",
		}, []string{"venue"}),
		ChildOrdersTotal: promauto.NewCounter(prometheus.CounterOpts{
			Namespace: "sor",
			Name:      "child_orders_total",
			Help:      "Total child orders generated by the splitter/algos.",
		}),
	}
}

// ── Instrumentation helpers ───────────────────────────────────────────────────

// ObserveRoute records metrics for a completed Route call.
func (m *Metrics) ObserveRoute(result RouteResult, routingDur, executionDur time.Duration) {
	if m == nil {
		return
	}
	m.RoutingLatency.Observe(routingDur.Seconds())
	m.ExecutionLatency.Observe(executionDur.Seconds())
	algo := string(result.Plan.Algo)
	if algo == "" {
		algo = "IMMEDIATE"
	}
	m.RoutesTotal.WithLabelValues(string(result.WinningVenue), algo).Inc()
	m.ChildOrdersTotal.Add(float64(len(result.Plan.Children)))
	for _, f := range result.Report.Fills {
		v := string(f.VenueID)
		if f.Status == "REJECTED" {
			m.RejectionsTotal.WithLabelValues(v).Inc()
			continue
		}
		m.SlippageBps.WithLabelValues(v).Observe(absSor(f.SlippageBps))
	}
}

// PublishVenues pushes the registry's current venue health/fill metrics.
func (m *Metrics) PublishVenues(reg *VenueRegistry) {
	if m == nil {
		return
	}
	for _, v := range reg.All() {
		m.VenueHealth.WithLabelValues(string(v.ID)).Set(v.Metrics.HealthScore)
		m.FillRate.WithLabelValues(string(v.ID)).Set(v.Metrics.FillRate)
	}
}

// RecordFailover increments the failover counter.
func (m *Metrics) RecordFailover(from, to VenueID) {
	if m == nil {
		return
	}
	m.FailoverTotal.WithLabelValues(string(from), string(to)).Inc()
}

// ── Grafana / AlertManager provisioning ───────────────────────────────────────

// GrafanaDashboardJSON returns a minimal Grafana dashboard for SOR panels.
func GrafanaDashboardJSON() string {
	panels := []string{
		grafanaTimeseries("Routing Latency p99", `histogram_quantile(0.99, rate(sor_routing_latency_seconds_bucket[5m]))`),
		grafanaTimeseries("Execution Latency p99", `histogram_quantile(0.99, rate(sor_execution_latency_seconds_bucket[5m]))`),
		grafanaGaugeVec("Venue Health", `sor_venue_health_score`, "venue"),
		grafanaGaugeVec("Venue Fill Rate", `sor_venue_fill_rate`, "venue"),
		grafanaTimeseries("Slippage p95", `histogram_quantile(0.95, rate(sor_slippage_bps_bucket[5m]))`),
		grafanaTimeseries("Failover Rate", `rate(sor_failover_total[5m])`),
		grafanaGaugeVec("Liquidity Score", `sor_liquidity_score`, "venue"),
		grafanaStat("Cost Savings (bps)", `sor_cost_savings_bps`),
	}
	return fmt.Sprintf(`{"title":"SOR - Smart Order Routing","panels":[%s]}`, strings.Join(panels, ","))
}

// AlertRulesYAML returns Prometheus AlertManager rules for the SOR.
func AlertRulesYAML() string {
	return `groups:
- name: sor_alerts
  rules:
  - alert: SORVenueUnhealthy
    expr: sor_venue_health_score < 50
    for: 1m
    labels: {severity: warning}
    annotations:
      summary: "Venue {{ $labels.venue }} health below 50"
  - alert: SORVenueDown
    expr: sor_venue_health_score < 30
    for: 30s
    labels: {severity: critical}
    annotations:
      summary: "Venue {{ $labels.venue }} is DOWN (health < 30)"
  - alert: SORHighSlippage
    expr: histogram_quantile(0.95, rate(sor_slippage_bps_bucket[5m])) > 20
    for: 2m
    labels: {severity: warning}
    annotations:
      summary: "SOR p95 slippage above 20 bps"
  - alert: SORHighFailoverRate
    expr: rate(sor_failover_total[5m]) > 0.5
    for: 1m
    labels: {severity: warning}
    annotations:
      summary: "SOR failover rate elevated"
  - alert: SORLowFillRate
    expr: sor_venue_fill_rate < 0.8
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Venue {{ $labels.venue }} fill rate below 80%"
`
}

func grafanaTimeseries(title, expr string) string {
	return fmt.Sprintf(`{"type":"timeseries","title":%q,"targets":[{"expr":%q}]}`, title, expr)
}

func grafanaGaugeVec(title, metric, label string) string {
	return fmt.Sprintf(`{"type":"gauge","title":%q,"targets":[{"expr":%q,"legendFormat":"{{%s}}"}]}`, title, metric, label)
}

func grafanaStat(title, expr string) string {
	return fmt.Sprintf(`{"type":"stat","title":%q,"targets":[{"expr":%q}]}`, title, expr)
}
