package ai

import (
	"fmt"
	"sort"
	"strings"
)

type StrategySupportLevel string

const (
	StrategySupportRuleReady    StrategySupportLevel = "RULE_READY"
	StrategySupportExternalData StrategySupportLevel = "EXTERNAL_DATA_REQUIRED"
	StrategySupportBlueprint    StrategySupportLevel = "ENGINE_BLUEPRINT"
)

type AIStrategyBlueprint struct {
	ID               int                  `json:"id"`
	Slug             string               `json:"slug"`
	Name             string               `json:"name"`
	Category         string               `json:"category"`
	Style            string               `json:"style"`
	Timeframe        string               `json:"timeframe"`
	CoreEdge         string               `json:"coreEdge"`
	EntryModel       string               `json:"entryModel"`
	ExitModel        string               `json:"exitModel"`
	RiskModel        string               `json:"riskModel"`
	PrimarySignals   []string             `json:"primarySignals"`
	DataRequirements []string             `json:"dataRequirements"`
	SupportLevel     StrategySupportLevel `json:"supportLevel"`
}

type StrategyLibrarySummary struct {
	Total          int            `json:"total"`
	ByCategory     map[string]int `json:"byCategory"`
	ByStyle        map[string]int `json:"byStyle"`
	BySupportLevel map[string]int `json:"bySupportLevel"`
}

func newBlueprint(
	id int,
	slug string,
	name string,
	category string,
	style string,
	timeframe string,
	coreEdge string,
	entryModel string,
	exitModel string,
	riskModel string,
	primarySignals []string,
	dataRequirements []string,
	support StrategySupportLevel,
) AIStrategyBlueprint {
	return AIStrategyBlueprint{
		ID:               id,
		Slug:             slug,
		Name:             name,
		Category:         category,
		Style:            style,
		Timeframe:        timeframe,
		CoreEdge:         coreEdge,
		EntryModel:       entryModel,
		ExitModel:        exitModel,
		RiskModel:        riskModel,
		PrimarySignals:   primarySignals,
		DataRequirements: dataRequirements,
		SupportLevel:     support,
	}
}

var aiStrategyLibrary = []AIStrategyBlueprint{
	newBlueprint(1, "ai-order-flow-scalping", "AI Order Flow Scalping", "Microstructure", "Scalp", "1m with tick and L2 confirmation",
		"Trade directional pressure before price fully reprices.",
		"Enter when bid-ask imbalance, delta, whale flow, and price all align.",
		"Exit on absorption, opposing delta, or nearby wall rejection.",
		"Stops sit beyond the nearest real liquidity cluster.",
		[]string{"bid/ask imbalance", "volume delta", "whale clusters", "spoof filter"},
		[]string{"L2 order book", "trade tape", "websocket feed"},
		StrategySupportExternalData),
	newBlueprint(2, "ai-vwap-liquidity-sweep", "AI VWAP + Liquidity Sweep Strategy", "VWAP", "Intraday", "1m entry, 5m structure",
		"Fade stop hunts that stretch too far from fair value.",
		"Enter after a sweep rejects and price reclaims the level while stretched from VWAP.",
		"Take partial at VWAP and trail toward the next structure target.",
		"Stops go beyond the sweep wick because the setup fails if revisited.",
		[]string{"session VWAP", "key level sweep", "rejection close", "reversion"},
		[]string{"OHLCV candles", "session clock"},
		StrategySupportRuleReady),
	newBlueprint(3, "ai-momentum-burst-scalping", "AI Momentum Burst Scalping", "Momentum", "Scalp", "1m",
		"Capture ignition candles before the move fully extends.",
		"Enter on RSI acceleration plus abnormal volume and true body expansion.",
		"Exit when momentum decays, diverges, or stalls after entry.",
		"Use ATR-based stops and avoid late entries after extension.",
		[]string{"RSI acceleration", "volume spike", "candle expansion", "ATR"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(4, "ai-market-structure-break", "AI Market Structure Break", "Structure", "Intraday", "1m entry, 5m structure",
		"Trade continuation after a clean break of structure and retest.",
		"Enter after BOS or ChoCH confirmation and a rejection retest.",
		"Target the next structure level and trail after confirmation.",
		"Skip ranges and invalidate beyond the retest wick.",
		[]string{"higher highs/lows", "BOS", "ChoCH", "retest candle"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(5, "ai-volatility-compression-breakout", "AI Volatility Compression Breakout", "Volatility", "Scalp", "1m or 5m",
		"Compression stores energy that breaks into expansion.",
		"Enter on the post-squeeze breakout only if volume confirms.",
		"Use fixed reward-to-risk or a volatility trail and kill failed breaks quickly.",
		"Stops sit inside the compression zone because failed breaks should not linger.",
		[]string{"Bollinger squeeze", "low ATR", "volume contraction", "breakout close"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(6, "ai-funding-rate-sentiment-edge", "AI Funding Rate + Sentiment Edge", "Sentiment", "Intraday", "1m entry with 1h to 4h context",
		"Fade overcrowded leverage when sentiment gets one-sided.",
		"Enter against the crowd when funding, OI, and positioning are extreme and price confirms exhaustion.",
		"Exit on mean reversion or once crowding metrics normalize.",
		"Size down unless both sentiment and price action align cleanly.",
		[]string{"funding rate", "open interest", "long-short ratio", "rejection candle"},
		[]string{"funding API", "OI feed", "positioning data"},
		StrategySupportExternalData),
	newBlueprint(7, "ai-liquidation-hunt-strategy", "AI Liquidation Hunt Strategy", "Microstructure", "Scalp", "1m with heatmap confirmation",
		"Forced liquidations create fast cascades and sharp reversals.",
		"Enter when price tags a dense liquidation zone and order flow confirms.",
		"Exit after the cascade exhausts or aggressive flow fades.",
		"Stops sit outside the liquidation pocket because noise inside is normal.",
		[]string{"liquidation clusters", "stop-loss zones", "order flow"},
		[]string{"liquidation heatmap", "order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(8, "ai-mean-reversion-micro-scalp", "AI Mean Reversion Micro-Scalp", "Mean Reversion", "Scalp", "1m",
		"Exploit short-term overextension away from local fair value in non-trends.",
		"Enter at adaptive VWAP extremes with RSI exhaustion and nearby micro support or resistance.",
		"Exit quickly back at the mean instead of overstaying the fade.",
		"Use small stops outside local micro-structure and skip strong trends.",
		[]string{"VWAP bands", "adaptive RSI", "micro support", "regime filter"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(9, "ai-multi-factor-confluence-engine", "AI Multi-Factor Confluence Engine", "Confluence", "Intraday", "1m to 15m",
		"Only trade when several independent sources of edge agree.",
		"Enter when at least three of VWAP, order flow, structure, and profile point the same way.",
		"Exit dynamically as the confirming factors begin to fail.",
		"Require a score threshold before any order is allowed through.",
		[]string{"VWAP", "order flow", "market structure", "volume profile", "AI score"},
		[]string{"OHLCV candles", "order flow", "volume profile"},
		StrategySupportExternalData),
	newBlueprint(10, "ai-adaptive-strategy-self-learning", "AI Adaptive Strategy", "Adaptive", "Engine", "multi-timeframe",
		"Detect the regime, switch the playbook, and retrain lightweight models carefully.",
		"Route signals through trend, range, or breakout modules based on regime confidence.",
		"Exit using the active sub-strategy or when regime confidence collapses.",
		"Keep adaptation lightweight and conservative to avoid overfitting.",
		[]string{"regime detection", "feature engineering", "strategy switching", "retraining"},
		[]string{"historical feature store", "model inference"},
		StrategySupportBlueprint),
	newBlueprint(11, "ai-volume-profile-rejection", "AI Volume Profile Rejection Strategy", "Market Profile", "Intraday", "1m to 15m",
		"HVNs and LVNs reveal where the market accepts or rejects price.",
		"Enter on HVN rejection or LVN break with momentum toward the next node.",
		"Exit into the next meaningful profile node.",
		"Skip dead sessions because profile reactions are less trustworthy in thin liquidity.",
		[]string{"POC", "VAH", "VAL", "HVN", "LVN"},
		[]string{"volume profile data", "OHLCV candles"},
		StrategySupportExternalData),
	newBlueprint(12, "ai-delta-divergence-scalping", "AI Delta Divergence Scalping", "Microstructure", "Scalp", "1m",
		"Price can keep pushing while aggressive participation weakens beneath the surface.",
		"Enter when price makes a fresh push but cumulative delta diverges and flow stops confirming.",
		"Exit on the first real reversal confirmation.",
		"Keep stops close because divergence is early by nature.",
		[]string{"price versus delta divergence", "aggressive flow", "reversal trigger"},
		[]string{"trade tape", "delta stream"},
		StrategySupportExternalData),
	newBlueprint(13, "ai-iceberg-order-detection", "AI Iceberg Order Detection", "Microstructure", "Scalp", "tick to 1m",
		"Repeated fills at the same level can reveal hidden institutional absorption.",
		"Enter once repeated executions suggest an iceberg is being defended and price starts breaking away.",
		"Exit when the move away from the zone loses force.",
		"Stops sit just beyond the defended band because the thesis dies if absorption disappears.",
		[]string{"repeated fills", "hidden liquidity", "absorption zone"},
		[]string{"full trade tape", "order book updates"},
		StrategySupportExternalData),
	newBlueprint(14, "ai-fair-value-gap", "AI Fair Value Gap Strategy", "Structure", "Intraday", "1m to 15m",
		"Impulsive imbalance zones often get revisited before continuation.",
		"Enter when price returns to a valid FVG aligned with structure and bias.",
		"Exit on continuation toward the prior impulse target or next shelf.",
		"Stops go beyond the gap invalidation edge rather than the midpoint.",
		[]string{"three-candle imbalance", "FVG zone", "structure alignment"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(15, "ai-time-of-day-edge", "AI Time-of-Day Edge Strategy", "Session", "Intraday", "1m to 15m",
		"Bitcoin behaves differently across Asia, London, and New York.",
		"Enter only during statistically favorable windows when volatility matches the playbook.",
		"Exit by session target, time stop, or volatility decay.",
		"Reduce size outside prime windows and skip dead hours entirely.",
		[]string{"London open", "New York move", "Asian range", "volatility filter"},
		[]string{"OHLCV candles", "session clock"},
		StrategySupportRuleReady),
	newBlueprint(16, "ai-liquidity-void", "AI Liquidity Void Strategy", "Microstructure", "Scalp", "tick to 1m",
		"Thin-book zones allow price to move quickly with little resistance.",
		"Enter when price enters a mapped void with momentum and no opposing wall nearby.",
		"Exit into the next meaningful liquidity pocket.",
		"Tight invalidation is required because a refill of liquidity often kills the edge.",
		[]string{"thin order book", "void entry", "speed confirmation", "next cluster"},
		[]string{"L2 order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(17, "ai-order-book-pressure", "AI Order Book Pressure Strategy", "Microstructure", "Scalp", "tick to 1m",
		"Persistent stacking and sudden pulling of liquidity can lead price by seconds.",
		"Enter when stacked bids or asks dominate and the opposing side pulls liquidity.",
		"Exit once pressure normalizes or gets absorbed.",
		"Ignore signals that fail the spoof filter or appear in noisy spread conditions.",
		[]string{"bid stacking", "ask stacking", "liquidity removal", "spoof filter"},
		[]string{"L2 order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(18, "ai-breakout-failure", "AI Breakout Failure Strategy", "Price Action", "Intraday", "1m to 5m",
		"False breaks trap late traders and reverse back through the range.",
		"Enter after a breakout fails to hold and rejection volume confirms the trap.",
		"Exit back inside the range or into the opposite side if momentum persists.",
		"Stops belong beyond the failed breakout wick, not inside the range noise.",
		[]string{"fake breakout", "rejection candle", "volume confirmation", "range return"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(19, "ai-open-interest-price-divergence", "AI Open Interest + Price Divergence", "Sentiment", "Intraday", "1m entry with 1h context",
		"Open interest shows whether price is driven by fresh risk or by covering.",
		"Enter when price and OI diverge in a way that suggests weakness or forced continuation.",
		"Exit once the divergence resolves or price confirms the opposite reading.",
		"Pair with funding where possible because OI alone can mislead.",
		[]string{"price change", "open interest change", "funding context"},
		[]string{"open interest feed", "funding feed", "OHLCV candles"},
		StrategySupportExternalData),
	newBlueprint(20, "ai-micro-trend-following-scalp", "AI Micro Trend Following Scalp", "Trend", "Scalp", "1m",
		"Capture small but repeated impulse legs inside a clean micro trend.",
		"Enter on pullbacks after EMA 9/21 alignment and a supportive micro-structure bounce.",
		"Exit into the next impulse extension rather than waiting for swings.",
		"Skip sideways environments and keep stops inside the pullback invalidation zone.",
		[]string{"EMA 9/21", "micro trend", "pullback entry", "trend filter"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(21, "ai-range-liquidity-strategy", "AI Range Liquidity Strategy", "Range", "Intraday", "1m to 5m",
		"Range-bound markets repeatedly harvest liquidity at equal highs and lows.",
		"Enter at support or resistance only when fake-breakout behavior confirms the range is still intact.",
		"Exit near the opposite edge instead of asking a range trade to become a trend trade.",
		"Stops sit outside the range boundary and size should shrink as volatility expands.",
		[]string{"equal highs", "equal lows", "support", "resistance", "fake breakout"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(22, "ai-news-volatility-explosion", "AI News + Volatility Explosion", "Event", "Intraday", "1m",
		"Post-news spikes often overshoot, then either continue cleanly or mean revert hard.",
		"Enter only after the initial shock stabilizes and a cleaner continuation or fade pattern forms.",
		"Exit on momentum fade because news edges decay fast.",
		"Use hard risk caps because slippage and spread risk dominate this setup.",
		[]string{"news event", "stabilization", "volume spike", "post-event direction"},
		[]string{"news calendar", "OHLCV candles", "live spreads"},
		StrategySupportExternalData),
	newBlueprint(23, "ai-correlation-arbitrage-btc-eth", "AI Correlation Arbitrage BTC vs ETH", "Intermarket", "Intraday", "1m to 15m",
		"When BTC and ETH temporarily de-sync, the spread can mean revert.",
		"Enter when the leader-laggard relationship breaches a statistical threshold and correlation remains intact.",
		"Exit once the spread normalizes or correlation breaks.",
		"Treat it as a relative-value trade and watch hedge ratio drift.",
		[]string{"BTC/ETH spread", "z-score", "rolling correlation", "hedge ratio"},
		[]string{"multi-asset price feed"},
		StrategySupportExternalData),
	newBlueprint(24, "ai-volatility-regime-switching", "AI Volatility Regime Switching", "Adaptive", "Engine", "multi-timeframe",
		"Volatility determines whether breakout or mean-reversion logic should dominate.",
		"Switch the active playbook when ATR and realized volatility move into a new regime band.",
		"Exit through the selected sub-strategy or when the regime changes mid-trade.",
		"Scale risk down when the regime is unstable to avoid flip-flopping.",
		[]string{"ATR", "realized volatility", "regime bands", "strategy switch"},
		[]string{"OHLCV candles"},
		StrategySupportBlueprint),
	newBlueprint(25, "ai-smart-money-concepts", "AI Smart Money Concept Strategy", "SMC", "Intraday", "1m to 15m",
		"Liquidity grabs, order blocks, and structure shifts create institutional-style entries.",
		"Enter after a liquidity grab and reaction into a validated order block with structure support.",
		"Exit at the next structure objective rather than relying on lagging indicators.",
		"Demand clear invalidation because SMC setups degrade quickly when levels get consumed.",
		[]string{"order block", "liquidity grab", "market structure", "institutional context"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(26, "ai-latency-arbitrage", "AI Latency Arbitrage", "Execution", "HFT", "sub-second",
		"Exploit small cross-exchange price lags before the spread closes.",
		"Enter by buying the lagging venue and selling the leading venue at the same moment.",
		"Exit immediately through hedge completion instead of directional conviction.",
		"This is infrastructure-first and not realistic without ultra-low-latency execution.",
		[]string{"cross-exchange lag", "microsecond update differences", "hedged entry"},
		[]string{"multi-exchange market data", "co-located execution"},
		StrategySupportExternalData),
	newBlueprint(27, "ai-spread-expansion-strategy", "AI Spread Expansion Strategy", "Execution", "Scalp", "tick",
		"Abnormal spread expansion can precede short-lived dislocations or normalization edges.",
		"Enter when spreads widen beyond normal and depth confirms a temporary liquidity vacuum.",
		"Exit when the spread compresses back toward normal conditions.",
		"Use strict slippage controls because bad fills destroy the edge.",
		[]string{"bid-ask spread", "abnormal widening", "market depth filter"},
		[]string{"best bid/ask", "depth feed"},
		StrategySupportExternalData),
	newBlueprint(28, "ai-stop-hunt-detection", "AI Stop-Hunt Detection Engine", "Price Action", "Intraday", "1m to 5m",
		"Liquidity pools at equal highs and lows often get swept before the real move begins.",
		"Enter after a stop hunt spike rejects and the follow-through candle confirms the reversal.",
		"Exit back toward equilibrium or the opposite side of the local range.",
		"Stops belong beyond the hunt extreme because the manipulation thesis fails if price accepts there.",
		[]string{"equal highs", "equal lows", "spike and reversal", "volume validation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(29, "ai-gamma-squeeze", "AI Gamma Squeeze Strategy", "Derivatives", "Intraday", "1m entry with options context",
		"Dealer positioning can mechanically accelerate price around major gamma levels.",
		"Enter when price moves through an important gamma level and dealer hedging is likely to amplify the move.",
		"Exit near exhaustion once the gamma-driven expansion loses urgency.",
		"Respect options-driven instability and reduce size unless data quality is high.",
		[]string{"gamma levels", "dealer positioning", "options strikes"},
		[]string{"options chain", "gamma exposure model"},
		StrategySupportExternalData),
	newBlueprint(30, "ai-dark-pool-large-flow-tracking", "AI Dark Pool / Large Flow Tracking", "Flow", "Intraday", "1m to 15m",
		"Large block activity and wallet flow can reveal institutional bias before price fully adjusts.",
		"Enter with the direction of meaningful flow only after price action confirms that the market is following it.",
		"Exit on momentum exhaustion or when large-flow confirmation disappears.",
		"Treat noisy on-chain bursts carefully and require confluence with spot price action.",
		[]string{"block trades", "large wallet moves", "directional bias"},
		[]string{"block trade feed", "on-chain flow data", "OHLCV candles"},
		StrategySupportExternalData),
	newBlueprint(31, "ai-micro-pullback-scalping", "AI Micro Pullback Scalping", "Trend", "Scalp", "1m",
		"Trend markets repeatedly offer small low-risk pullbacks into continuation.",
		"Enter when a strong short-term trend pauses into a shallow retracement and quickly re-accelerates.",
		"Exit into the next impulse rather than waiting for a swing trade.",
		"Use very tight stops because the setup depends on immediate continuation.",
		[]string{"strong trend", "shallow retracement", "tight stop", "continuation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(32, "ai-keltner-channel-breakout", "AI Keltner Channel Breakout", "Volatility", "Intraday", "1m to 5m",
		"Keltner channel expansion can identify fresh volatility regimes and trend breaks.",
		"Enter when price breaks out of the channel with volume and volatility confirmation.",
		"Exit through a volatility trail so strong expansions can keep paying.",
		"Ignore weak breaks without supporting volume because Keltner alone is not enough.",
		[]string{"Keltner channel", "channel break", "volatility increase", "volume confirmation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(33, "ai-order-book-imbalance-reversal", "AI Order Book Imbalance Reversal", "Microstructure", "Scalp", "tick to 1m",
		"Extreme one-sided book conditions can signal exhaustion once the move is already extended.",
		"Enter when the book shows extreme imbalance but price can no longer extend in that direction.",
		"Exit on the short reversal burst instead of expecting a full trend change.",
		"Demand fake-signal filtering because spoofed imbalance is common near turns.",
		[]string{"extreme imbalance", "price exhaustion", "reversal confirmation"},
		[]string{"L2 order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(34, "ai-funding-rate-scalp", "AI Funding Rate Scalp", "Sentiment", "Scalp", "1m entry with funding context",
		"Short-term crowding around extreme funding values can mean revert sharply.",
		"Enter opposite the crowd when funding is extreme and price prints a reversal trigger.",
		"Exit once the quick reversion move completes or crowding cools.",
		"Require price confirmation because funding alone can stay extreme for too long.",
		[]string{"funding spike", "crowded direction", "price action confirmation"},
		[]string{"funding rate API", "OHLCV candles"},
		StrategySupportExternalData),
	newBlueprint(35, "ai-vwap-band-scalping", "AI VWAP Band Scalping", "VWAP", "Scalp", "1m",
		"VWAP deviation bands offer a clean intraday mean-reversion framework.",
		"Enter when price rejects an upper or lower band in a non-trending environment.",
		"Exit back at the VWAP center instead of reaching for trend targets.",
		"Do not fade strong trend days where price can walk the band.",
		[]string{"VWAP bands", "extreme deviation", "reversion trigger", "trend filter"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(36, "ai-fractal-breakout-strategy", "AI Fractal Breakout Strategy", "Structure", "Intraday", "1m to 15m",
		"Local fractal highs and lows provide clear breakout anchors for structured continuation.",
		"Enter on a break of a high-quality fractal when higher-timeframe bias supports it.",
		"Exit at the next fractal shelf or with a trail once the move matures.",
		"Skip weak fractals in noisy ranges because they over-signal.",
		[]string{"fractal highs", "fractal lows", "breakout", "multi-timeframe confirmation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(37, "ai-liquidity-ladder-strategy", "AI Liquidity Ladder Strategy", "Microstructure", "Scalp", "tick to 1m",
		"Price can move cleanly through thin liquidity layers until it reaches a real wall.",
		"Enter when price starts stepping through a ladder of thin layers with momentum.",
		"Exit at the next major liquidity wall or when the ladder refills against the trade.",
		"Position size should adapt to available depth so the strategy does not become the impact.",
		[]string{"liquidity layers", "thin books", "major wall", "dynamic sizing"},
		[]string{"L2 order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(38, "ai-hft-style-micro-scalping", "AI HFT-Style Micro Scalping", "Execution", "HFT", "sub-second",
		"Capture tiny repeated inefficiencies with very fast turnover and strict risk.",
		"Enter only on micro dislocations that can be closed within seconds.",
		"Exit almost immediately once the edge normalizes.",
		"This is execution-dominated and only viable with extremely fast infrastructure.",
		[]string{"tick data", "micro price changes", "execution latency"},
		[]string{"tick feed", "ultra-low-latency execution"},
		StrategySupportExternalData),
	newBlueprint(39, "ai-regime-detection-strategy-switch", "AI Regime Detection + Strategy Switch", "Adaptive", "Engine", "multi-timeframe",
		"Use regime detection to route flow toward trend, range, or breakout engines automatically.",
		"Select the strategy family whose assumptions best match the current regime and confidence level.",
		"Exit using the selected strategy or fall back to defensive exits when the regime flips.",
		"Require stability across several bars before switching to avoid churn.",
		[]string{"trend detection", "volatility", "volume", "strategy routing"},
		[]string{"OHLCV candles", "regime classifier"},
		StrategySupportBlueprint),
	newBlueprint(40, "ai-ensemble-strategy", "AI Ensemble Strategy", "Confluence", "Engine", "multi-timeframe",
		"Weighted consensus across independent strategies reduces single-model fragility.",
		"Enter only when a basket of strategy votes clears a strong consensus threshold.",
		"Exit dynamically as vote quality decays or volatility changes.",
		"Rebalance weights conservatively using recent out-of-sample performance.",
		[]string{"weighted strategies", "consensus score", "AI scoring model"},
		[]string{"signal bus", "historical attribution", "performance tracking"},
		StrategySupportBlueprint),
	newBlueprint(41, "ai-liquidity-sweep-structure-shift", "AI Liquidity Sweep + Structure Shift", "Structure", "Intraday", "1m to 5m",
		"The highest-quality reversals often combine a stop hunt with an immediate structure change.",
		"Enter after a liquidity sweep is followed by an immediate ChoCH or BOS in the opposite direction.",
		"Exit at the next clean structural target or when follow-through fails quickly.",
		"Keep invalidation at the sweep extreme because the market should not revisit it if the reversal is real.",
		[]string{"liquidity sweep", "ChoCH", "BOS", "reversal trigger"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(42, "ai-order-flow-momentum-stacking", "AI Order Flow Momentum Stacking", "Microstructure", "Scalp", "tick to 1m",
		"Consecutive aggressive prints often stack before the broader market reacts.",
		"Enter when repeated same-side aggressive flow keeps building with no opposing absorption.",
		"Exit as soon as the stacking cadence slows or reverses.",
		"Do not hold through neutralization because the edge is front-loaded.",
		[]string{"consecutive aggressive flow", "stacked momentum", "flow slowdown"},
		[]string{"trade tape", "aggressor side"},
		StrategySupportExternalData),
	newBlueprint(43, "ai-absorption-reversal", "AI Absorption Reversal Strategy", "Microstructure", "Scalp", "1m",
		"Large volume with little movement often signals hidden absorption before reversal.",
		"Enter once absorption is confirmed and price starts pushing away from the defended area.",
		"Exit on the short reversal leg instead of waiting for a full structural move.",
		"Stops should sit beyond the absorption shelf because that is the real invalidation.",
		[]string{"large volume", "small price movement", "hidden absorption", "reversal push"},
		[]string{"trade tape", "OHLCV candles"},
		StrategySupportExternalData),
	newBlueprint(44, "ai-vwap-deviation-extreme", "AI VWAP Deviation Extreme Strategy", "VWAP", "Intraday", "1m to 5m",
		"Extreme distance from VWAP often snaps back when the market is not trending cleanly.",
		"Enter only at truly stretched VWAP deviations with a reversal trigger, not on mild extension.",
		"Exit toward VWAP or an inner deviation band.",
		"Use dynamic bands so the definition of extreme scales with volatility.",
		[]string{"extreme VWAP deviation", "dynamic bands", "reversal trigger"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(45, "ai-micro-consolidation-breakout", "AI Micro Consolidation Breakout", "Volatility", "Scalp", "1m",
		"Tight micro ranges often resolve with clean directional expansion.",
		"Enter on a breakout from a very small consolidation only when volume confirms the escape.",
		"Exit after the quick measured move rather than overstaying the burst.",
		"Use a tight stop inside the micro range because delayed breakouts fail often.",
		[]string{"tight range", "micro breakout", "volume confirmation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(46, "ai-delta-cluster-breakout", "AI Delta Cluster Breakout", "Microstructure", "Scalp", "1m",
		"Large one-sided participation clusters can mark the launch point for a breakout.",
		"Enter when price leaves a delta cluster in the same direction as aggressive participation.",
		"Exit on momentum exhaustion or once delta stops expanding.",
		"Keep invalidation close to the cluster because the breakout should not fall back quickly.",
		[]string{"delta cluster", "aggressive participation", "breakout"},
		[]string{"trade tape", "delta aggregation"},
		StrategySupportExternalData),
	newBlueprint(47, "ai-liquidity-trap-reversal", "AI Liquidity Trap Reversal", "Price Action", "Intraday", "1m to 5m",
		"Failed moves through obvious levels leave trapped participants that fuel the reversal.",
		"Enter once the fake break is obvious and the first opposing candle confirms trapped flow.",
		"Exit back into the prior value area or range midpoint.",
		"Stop beyond the trap high or low because reclaiming it re-validates the original move.",
		[]string{"fake breakout", "trapped traders", "reversal confirmation"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(48, "ai-order-book-vacuum-strategy", "AI Order Book Vacuum Strategy", "Microstructure", "Scalp", "tick to 1m",
		"When liquidity suddenly disappears, price can gap through the vacuum to the next pool.",
		"Enter when the book opens up in one direction and flow starts taking the path of least resistance.",
		"Exit into the next meaningful liquidity zone because that is where resistance should reappear.",
		"Demand confirmation that the vacuum is real, not just a transient book flicker.",
		[]string{"sudden lack of liquidity", "vacuum zone", "next liquidity target"},
		[]string{"L2 order book", "trade tape"},
		StrategySupportExternalData),
	newBlueprint(49, "ai-high-probability-scalp-filter", "AI High Probability Scalp Filter", "Risk Filter", "Engine", "cross-strategy",
		"Trade selection quality often matters more than raw signal quantity.",
		"Allow execution only when a multi-factor score clears a strict threshold.",
		"Exit logic belongs to the underlying strategy; this layer decides if the trade deserves capital.",
		"Use it to block mediocre setups rather than to rescue bad ones after entry.",
		[]string{"multi-factor score", "quality gate", "trade filter"},
		[]string{"signal metadata", "market context"},
		StrategySupportBlueprint),
	newBlueprint(50, "ai-volatility-spike-fade", "AI Volatility Spike Fade", "Volatility", "Intraday", "1m",
		"Extreme short-term volatility often overshoots before reverting toward normal conditions.",
		"Enter after a clear spike when price and volatility both show signs of exhaustion.",
		"Exit on reversion to normal range behavior rather than aiming for continuation.",
		"Keep hard stops because spikes can persist longer than expected.",
		[]string{"volatility spike", "overreaction", "fade trigger"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(51, "ai-trend-exhaustion-detection", "AI Trend Exhaustion Detection", "Reversal", "Intraday", "1m to 5m",
		"Trends often end when new highs or lows stop receiving real participation.",
		"Enter after divergence and volume decay confirm that the current trend is running out of force.",
		"Exit on the first meaningful counter-move rather than demanding a full reversal.",
		"Do not front-run too early; require both exhaustion and price confirmation.",
		[]string{"divergence", "volume decline", "exhaustion candle"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(52, "ai-multi-timeframe-confluence", "AI Multi-Timeframe Confluence", "Confluence", "Intraday", "1m, 5m, 15m",
		"Alignment across several timeframes increases signal quality and reduces noise.",
		"Enter when 1m, 5m, and 15m structure or trend all align in the same direction.",
		"Exit on the first clear higher-timeframe weakness or lower-timeframe invalidation.",
		"Keep size moderate because higher accuracy can still produce slower entries.",
		[]string{"1m alignment", "5m alignment", "15m alignment", "confluence gate"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(53, "ai-hidden-liquidity-detection", "AI Hidden Liquidity Detection", "Microstructure", "Scalp", "tick to 1m",
		"Hidden liquidity often appears as iceberg-style refresh plus absorption behavior.",
		"Enter when both hidden-liquidity clues and breakout direction confirm institutional positioning.",
		"Exit once price cleanly breaks away from the defended zone or the defense disappears.",
		"Only trust high-confidence detections because hidden-liquidity inference is noisy.",
		[]string{"iceberg behavior", "absorption", "hidden liquidity", "breakaway"},
		[]string{"trade tape", "order book"},
		StrategySupportExternalData),
	newBlueprint(54, "ai-range-expansion-strategy", "AI Range Expansion Strategy", "Volatility", "Intraday", "1m to 5m",
		"Markets often transition from compression to expansion through clearly defined range breaks.",
		"Enter once a mature range resolves with real volume and directional conviction.",
		"Exit using a measured move target or volatility trail.",
		"Do not chase half-breaks that never leave the range cleanly.",
		[]string{"range boundary", "breakout", "measured move", "volume expansion"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(55, "ai-micro-reversal-scalp", "AI Micro Reversal Scalp", "Reversal", "Scalp", "30s to 1m",
		"Very short-term reversals offer frequent small profit opportunities if entries are precise.",
		"Enter on fast rejection signals after a brief directional exhaustion move.",
		"Exit quickly with small targets because the setup is not built for trend riding.",
		"Keep hold times tiny and cut immediately if the reversal stalls.",
		[]string{"quick reversal signal", "small target", "exhaustion wick"},
		[]string{"short timeframe candles"},
		StrategySupportRuleReady),
	newBlueprint(56, "ai-price-velocity-strategy", "AI Price Velocity Strategy", "Velocity", "Scalp", "tick to 1m",
		"Speed of movement can matter more than static level analysis in fast markets.",
		"Enter when price velocity and acceleration cross a directional threshold.",
		"Exit when velocity decelerates even if price has not fully reversed.",
		"Use it as a speed sensor and avoid random noise bursts.",
		[]string{"price velocity", "acceleration", "deceleration exit"},
		[]string{"tick data", "short timeframe candles"},
		StrategySupportRuleReady),
	newBlueprint(57, "ai-volume-burst-continuation", "AI Volume Burst Continuation", "Momentum", "Scalp", "1m",
		"Real volume expansion inside trend often supports continuation rather than reversal.",
		"Enter when a trend-aligned burst prints with above-normal participation.",
		"Exit when momentum fades or the burst fails to attract follow-through.",
		"Keep stops near the burst origin because continuation should be immediate.",
		[]string{"volume burst", "trend alignment", "continuation trigger"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(58, "ai-micro-support-resistance-scalp", "AI Micro Support Resistance Scalp", "Price Action", "Scalp", "1m",
		"Small repeated reaction levels can anchor precise high-frequency entries.",
		"Enter on a clean bounce or break from a validated micro support or resistance level.",
		"Exit with small tactical targets before noise overwhelms the trade.",
		"Keep stops tight because micro levels lose value quickly once breached.",
		[]string{"micro support", "micro resistance", "bounce", "break"},
		[]string{"OHLCV candles"},
		StrategySupportRuleReady),
	newBlueprint(59, "ai-execution-optimization-engine", "AI Execution Optimization Engine", "Execution", "Engine", "cross-strategy",
		"Better execution improves realized edge without changing the signal model.",
		"Route orders through sizing, splitting, and timing logic instead of naive market orders.",
		"Exit is delegated to the strategy; this layer optimizes how positions are entered and managed.",
		"Track slippage and market impact continuously so the engine degrades safely when fills worsen.",
		[]string{"slippage reduction", "order splitting", "smart routing", "impact control"},
		[]string{"order book", "fill analytics", "execution venue data"},
		StrategySupportBlueprint),
	newBlueprint(60, "ai-risk-first-strategy-engine", "AI Risk-First Strategy Engine", "Risk", "Engine", "portfolio-wide",
		"Capital preservation is the foundation that keeps every other strategy alive.",
		"Gate every trade through position sizing, drawdown limits, exposure checks, and quality validation.",
		"Exit and halt behavior are driven by risk state as much as by signal state.",
		"Treat this as non-optional infrastructure, not a nice-to-have addon.",
		[]string{"position sizing", "drawdown halt", "exposure control", "quality gate"},
		[]string{"portfolio state", "signal metadata", "PnL tracking"},
		StrategySupportBlueprint),
}

func GetAIStrategyLibrary() []AIStrategyBlueprint {
	out := make([]AIStrategyBlueprint, len(aiStrategyLibrary))
	copy(out, aiStrategyLibrary)
	return out
}

func SummarizeAIStrategyLibrary() StrategyLibrarySummary {
	summary := StrategyLibrarySummary{
		Total:          len(aiStrategyLibrary),
		ByCategory:     make(map[string]int),
		ByStyle:        make(map[string]int),
		BySupportLevel: make(map[string]int),
	}
	for _, strategy := range aiStrategyLibrary {
		summary.ByCategory[strategy.Category]++
		summary.ByStyle[strategy.Style]++
		summary.BySupportLevel[string(strategy.SupportLevel)]++
	}
	return summary
}

func BuildAIStrategyCatalogPrompt(limit int) string {
	if limit <= 0 || limit > len(aiStrategyLibrary) {
		limit = len(aiStrategyLibrary)
	}

	var builder strings.Builder
	builder.WriteString("RAIG AI strategy library:\n")
	for _, strategy := range aiStrategyLibrary[:limit] {
		builder.WriteString(fmt.Sprintf(
			"%d. %s [%s | %s | %s] edge=%s signals=%s support=%s\n",
			strategy.ID,
			strategy.Name,
			strategy.Category,
			strategy.Style,
			strategy.Timeframe,
			strategy.CoreEdge,
			strings.Join(strategy.PrimarySignals, ", "),
			strategy.SupportLevel,
		))
	}
	return builder.String()
}

func GetAIStrategySlugs() []string {
	slugs := make([]string, 0, len(aiStrategyLibrary))
	for _, strategy := range aiStrategyLibrary {
		slugs = append(slugs, strategy.Slug)
	}
	return slugs
}

func GetAIStrategyCategories() []string {
	seen := make(map[string]struct{})
	for _, strategy := range aiStrategyLibrary {
		seen[strategy.Category] = struct{}{}
	}
	categories := make([]string, 0, len(seen))
	for category := range seen {
		categories = append(categories, category)
	}
	sort.Strings(categories)
	return categories
}
