package options_selling

const (
	minLiveExpiryMinutes = 60
	maxLiveStrikePctOTM  = 0.020 // Sellers can go further out
)

var optionStrategyCategories = map[string]string{
	// ── original 30 ──
	"MomentumBurst_Bull_Put_Sell":     "Momentum",
	"MomentumBurst_Bear_Call_Sell":    "Momentum",
	"ConsecCandle_Bull_Put_Sell":      "Momentum",
	"ConsecCandle_Bear_Call_Sell":     "Momentum",
	"RSIRecovery_Bull_Put_Sell":       "Mean Reversion",
	"RSIFade_Bear_Call_Sell":          "Mean Reversion",
	"Overextension_Fade_Call_Sell":    "Mean Reversion",
	"Overextension_Fade_Put_Sell":     "Mean Reversion",
	"EMA_BullCross_Put_Sell":          "Breakout",
	"EMA_BearCross_Call_Sell":         "Breakout",
	"Resistance_Breakout_Put_Sell":    "Breakout",
	"Support_Breakdown_Call_Sell":     "Breakout",
	"Capitulation_VReversal_Put_Sell": "Capitulation",
	"SessionOpen_Bull_Put_Sell":       "Breakout",
	"SessionOpen_Bear_Call_Sell":      "Breakout",
	"VolCompress_Breakout_Bull_Put":   "Breakout",
	"VolCompress_Breakout_Bear_Call":  "Breakout",
	"VWAP_Continuation_Bull_Put":      "Momentum",
	"VWAP_Continuation_Bear_Call":     "Momentum",
	"TripleConfluence_Bull_Put":       "Hybrid",
	"TripleConfluence_Bear_Call":      "Hybrid",
	"TrendAlignment_Bull_Put":         "Breakout",
	"TrendAlignment_Bear_Call":        "Breakout",
	"BBSqueeze_Release_Bull_Put":      "Breakout",
	"BBSqueeze_Release_Bear_Call":     "Breakout",
	"MomentumVWAP_Pro_Bull_Put":       "Momentum",
	"MomentumVWAP_Pro_Bear_Call":      "Momentum",
	"BreakoutTrend_Pro_Bull_Put":      "Breakout",
	"BreakdownTrend_Pro_Bear_Call":    "Breakout",
	"Capitulation_Reclaim_Elite_Put":  "Capitulation",
	// ── 100 new (IDs 131-230) ──
	"BullMom_Quick_Put":          "Momentum",
	"BearMom_Quick_Call":         "Momentum",
	"RSI_Bounce_Bull_Put":        "Mean Reversion",
	"RSI_Fade_Bear_Call":         "Mean Reversion",
	"BBLower_Bounce_Put":         "Mean Reversion",
	"BBUpper_Fade_Call":          "Mean Reversion",
	"Stoch_Bounce_Bull_Put":      "Mean Reversion",
	"Stoch_Fade_Bear_Call":       "Mean Reversion",
	"HighIV_Trend_Bull_Put":      "Hybrid",
	"HighIV_Trend_Bear_Call":     "Hybrid",
	"SharpRev_Bull_Put":          "Capitulation",
	"SharpRev_Bear_Call":         "Capitulation",
	"BullMom_Mid_Put":            "Momentum",
	"BearMom_Mid_Call":           "Momentum",
	"BullMom_Wide_Put":           "Momentum",
	"BearMom_Wide_Call":          "Momentum",
	"RSI_Quick_Bull_Put":         "Mean Reversion",
	"RSI_Quick_Bear_Call":        "Mean Reversion",
	"Stoch_Quick_Bull_Put":       "Mean Reversion",
	"Stoch_Quick_Bear_Call":      "Mean Reversion",
	"SharpRev_Wide_Bull_Put":     "Capitulation",
	"SharpRev_Wide_Bear_Call":    "Capitulation",
	"HighIV_Quick_Bull_Put":      "Hybrid",
	"HighIV_Quick_Bear_Call":     "Hybrid",
	"EMABull_Quick_Put":          "Breakout",
	"EMABear_Quick_Call":         "Breakout",
	"EMABull_Wide_Put":           "Breakout",
	"EMABear_Wide_Call":          "Breakout",
	"EMAAbove_Quick_Put":         "Breakout",
	"EMABelow_Quick_Call":        "Breakout",
	"EMAAbove_Wide_Put":          "Breakout",
	"EMABelow_Wide_Call":         "Breakout",
	"ResBrk_Quick_Put":           "Breakout",
	"SupBrk_Quick_Call":          "Breakout",
	"ResBrk_Wide_Put":            "Breakout",
	"SupBrk_Wide_Call":           "Breakout",
	"ResBrk_Mid_Put":             "Breakout",
	"SupBrk_Mid_Call":            "Breakout",
	"BrkTrend_Quick_Bull_Put":    "Breakout",
	"BrkTrend_Quick_Bear_Call":   "Breakout",
	"BrkTrend_Wide_Bull_Put":     "Breakout",
	"BrkTrend_Wide_Bear_Call":    "Breakout",
	"BBLower_Mid_Put":            "Mean Reversion",
	"BBUpper_Mid_Call":           "Mean Reversion",
	"BBLower_Wide_Put":           "Mean Reversion",
	"BBUpper_Wide_Call":          "Mean Reversion",
	"BBSqueeze_Quick_Bull":       "Breakout",
	"BBSqueeze_Quick_Bear":       "Breakout",
	"VWAP_Quick_Bull_Put":        "Momentum",
	"VWAP_Quick_Bear_Call":       "Momentum",
	"VWAP_Wide_Bull_Put":         "Momentum",
	"VWAP_Wide_Bear_Call":        "Momentum",
	"MomVWAP_Quick_Bull_Put":     "Momentum",
	"MomVWAP_Quick_Bear_Call":    "Momentum",
	"MomVWAP_Wide_Bull_Put":      "Momentum",
	"MomVWAP_Wide_Bear_Call":     "Momentum",
	"MomBurst_Quick_Bull_Put":    "Momentum",
	"MomBurst_Quick_Bear_Call":   "Momentum",
	"MomBurst_Mid_Bull_Put":      "Momentum",
	"MomBurst_Mid_Bear_Call":     "Momentum",
	"Consec_Quick_Bull_Put":      "Momentum",
	"Consec_Quick_Bear_Call":     "Momentum",
	"Consec_Wide_Bull_Put":       "Momentum",
	"Consec_Wide_Bear_Call":      "Momentum",
	"VolComp_Quick_Bull_Put":     "Breakout",
	"VolComp_Quick_Bear_Call":    "Breakout",
	"VolComp_Wide_Bull_Put":      "Breakout",
	"VolComp_Wide_Bear_Call":     "Breakout",
	"Cap_Quick_Put":              "Capitulation",
	"Cap_Wide_Put":               "Capitulation",
	"Cap_Reclaim_Quick_Put":      "Capitulation",
	"OverextFade_Quick_Up_Call":  "Mean Reversion",
	"OverextFade_Quick_Down_Put": "Mean Reversion",
	"Triple_Quick_Bull_Put":      "Hybrid",
	"Triple_Quick_Bear_Call":     "Hybrid",
	"Triple_Wide_Bull_Put":       "Hybrid",
	"Triple_Wide_Bear_Call":      "Hybrid",
	"Session_Quick_Bull_Put":     "Breakout",
	"Session_Quick_Bear_Call":    "Breakout",
	"Session_Wide_Bull_Put":      "Breakout",
	"Session_Wide_Bear_Call":     "Breakout",
	"RSIExtreme_Quick_Bull_Put":  "Mean Reversion",
	"RSIExtreme_Quick_Bear_Call": "Mean Reversion",
	"RSIExtreme_Wide_Bull_Put":   "Mean Reversion",
	"RSIExtreme_Wide_Bear_Call":  "Mean Reversion",
	"Stoch_Wide_Bull_Put":        "Mean Reversion",
	"Stoch_Wide_Bear_Call":       "Mean Reversion",
	"BBSqueeze_Mid_Bull":         "Breakout",
	"BBSqueeze_Mid_Bear":         "Breakout",
	"HighIV_Wide_Bull_Put":       "Hybrid",
	"HighIV_Wide_Bear_Call":      "Hybrid",
	"BullMom_Alt_Put":            "Momentum",
	"BearMom_Alt_Call":           "Momentum",
	"RSI_Mid_Bull_Put":           "Mean Reversion",
	"RSI_Mid_Bear_Call":          "Mean Reversion",
	"SharpRev_Mid_Bull_Put":      "Capitulation",
	"SharpRev_Mid_Bear_Call":     "Capitulation",
	"Overext_Wide_Up_Call":       "Mean Reversion",
	"Overext_Wide_Down_Put":      "Mean Reversion",
	"Cap_Reclaim_Wide_Put":       "Capitulation",
}

var strategyIDs = map[string]int{
	// ── original 30 ──
	"MomentumBurst_Bull_Put_Sell":     101,
	"MomentumBurst_Bear_Call_Sell":    102,
	"ConsecCandle_Bull_Put_Sell":      103,
	"ConsecCandle_Bear_Call_Sell":     104,
	"RSIRecovery_Bull_Put_Sell":       105,
	"RSIFade_Bear_Call_Sell":          106,
	"Overextension_Fade_Call_Sell":    107,
	"Overextension_Fade_Put_Sell":     108,
	"EMA_BullCross_Put_Sell":          109,
	"EMA_BearCross_Call_Sell":         110,
	"Resistance_Breakout_Put_Sell":    111,
	"Support_Breakdown_Call_Sell":     112,
	"Capitulation_VReversal_Put_Sell": 113,
	"SessionOpen_Bull_Put_Sell":       114,
	"SessionOpen_Bear_Call_Sell":      115,
	"VolCompress_Breakout_Bull_Put":   116,
	"VolCompress_Breakout_Bear_Call":  117,
	"VWAP_Continuation_Bull_Put":      118,
	"VWAP_Continuation_Bear_Call":     119,
	"TripleConfluence_Bull_Put":       120,
	"TripleConfluence_Bear_Call":      121,
	"TrendAlignment_Bull_Put":         122,
	"TrendAlignment_Bear_Call":        123,
	"BBSqueeze_Release_Bull_Put":      124,
	"BBSqueeze_Release_Bear_Call":     125,
	"MomentumVWAP_Pro_Bull_Put":       126,
	"MomentumVWAP_Pro_Bear_Call":      127,
	"BreakoutTrend_Pro_Bull_Put":      128,
	"BreakdownTrend_Pro_Bear_Call":    129,
	"Capitulation_Reclaim_Elite_Put":  130,
	// ── 100 new (IDs 131-230) ──
	"BullMom_Quick_Put":          131,
	"BearMom_Quick_Call":         132,
	"RSI_Bounce_Bull_Put":        133,
	"RSI_Fade_Bear_Call":         134,
	"BBLower_Bounce_Put":         135,
	"BBUpper_Fade_Call":          136,
	"Stoch_Bounce_Bull_Put":      137,
	"Stoch_Fade_Bear_Call":       138,
	"HighIV_Trend_Bull_Put":      139,
	"HighIV_Trend_Bear_Call":     140,
	"SharpRev_Bull_Put":          141,
	"SharpRev_Bear_Call":         142,
	"BullMom_Mid_Put":            143,
	"BearMom_Mid_Call":           144,
	"BullMom_Wide_Put":           145,
	"BearMom_Wide_Call":          146,
	"RSI_Quick_Bull_Put":         147,
	"RSI_Quick_Bear_Call":        148,
	"Stoch_Quick_Bull_Put":       149,
	"Stoch_Quick_Bear_Call":      150,
	"SharpRev_Wide_Bull_Put":     151,
	"SharpRev_Wide_Bear_Call":    152,
	"HighIV_Quick_Bull_Put":      153,
	"HighIV_Quick_Bear_Call":     154,
	"EMABull_Quick_Put":          155,
	"EMABear_Quick_Call":         156,
	"EMABull_Wide_Put":           157,
	"EMABear_Wide_Call":          158,
	"EMAAbove_Quick_Put":         159,
	"EMABelow_Quick_Call":        160,
	"EMAAbove_Wide_Put":          161,
	"EMABelow_Wide_Call":         162,
	"ResBrk_Quick_Put":           163,
	"SupBrk_Quick_Call":          164,
	"ResBrk_Wide_Put":            165,
	"SupBrk_Wide_Call":           166,
	"ResBrk_Mid_Put":             167,
	"SupBrk_Mid_Call":            168,
	"BrkTrend_Quick_Bull_Put":    169,
	"BrkTrend_Quick_Bear_Call":   170,
	"BrkTrend_Wide_Bull_Put":     171,
	"BrkTrend_Wide_Bear_Call":    172,
	"BBLower_Mid_Put":            173,
	"BBUpper_Mid_Call":           174,
	"BBLower_Wide_Put":           175,
	"BBUpper_Wide_Call":          176,
	"BBSqueeze_Quick_Bull":       177,
	"BBSqueeze_Quick_Bear":       178,
	"VWAP_Quick_Bull_Put":        179,
	"VWAP_Quick_Bear_Call":       180,
	"VWAP_Wide_Bull_Put":         181,
	"VWAP_Wide_Bear_Call":        182,
	"MomVWAP_Quick_Bull_Put":     183,
	"MomVWAP_Quick_Bear_Call":    184,
	"MomVWAP_Wide_Bull_Put":      185,
	"MomVWAP_Wide_Bear_Call":     186,
	"MomBurst_Quick_Bull_Put":    187,
	"MomBurst_Quick_Bear_Call":   188,
	"MomBurst_Mid_Bull_Put":      189,
	"MomBurst_Mid_Bear_Call":     190,
	"Consec_Quick_Bull_Put":      191,
	"Consec_Quick_Bear_Call":     192,
	"Consec_Wide_Bull_Put":       193,
	"Consec_Wide_Bear_Call":      194,
	"VolComp_Quick_Bull_Put":     195,
	"VolComp_Quick_Bear_Call":    196,
	"VolComp_Wide_Bull_Put":      197,
	"VolComp_Wide_Bear_Call":     198,
	"Cap_Quick_Put":              199,
	"Cap_Wide_Put":               200,
	"Cap_Reclaim_Quick_Put":      201,
	"OverextFade_Quick_Up_Call":  202,
	"OverextFade_Quick_Down_Put": 203,
	"Triple_Quick_Bull_Put":      204,
	"Triple_Quick_Bear_Call":     205,
	"Triple_Wide_Bull_Put":       206,
	"Triple_Wide_Bear_Call":      207,
	"Session_Quick_Bull_Put":     208,
	"Session_Quick_Bear_Call":    209,
	"Session_Wide_Bull_Put":      210,
	"Session_Wide_Bear_Call":     211,
	"RSIExtreme_Quick_Bull_Put":  212,
	"RSIExtreme_Quick_Bear_Call": 213,
	"RSIExtreme_Wide_Bull_Put":   214,
	"RSIExtreme_Wide_Bear_Call":  215,
	"Stoch_Wide_Bull_Put":        216,
	"Stoch_Wide_Bear_Call":       217,
	"BBSqueeze_Mid_Bull":         218,
	"BBSqueeze_Mid_Bear":         219,
	"HighIV_Wide_Bull_Put":       220,
	"HighIV_Wide_Bear_Call":      221,
	"BullMom_Alt_Put":            222,
	"BearMom_Alt_Call":           223,
	"RSI_Mid_Bull_Put":           224,
	"RSI_Mid_Bear_Call":          225,
	"SharpRev_Mid_Bull_Put":      226,
	"SharpRev_Mid_Bear_Call":     227,
	"Overext_Wide_Up_Call":       228,
	"Overext_Wide_Down_Put":      229,
	"Cap_Reclaim_Wide_Put":       230,
}

func assignStrategyIDs(defs []StrategyDef) []StrategyDef {
	for i := range defs {
		defs[i].ID = strategyIDs[defs[i].Name]
	}
	return defs
}

func BuildStrategies() []StrategyDef {
	all := assignStrategyIDs(buildAllStrategies())
	filtered := make([]StrategyDef, 0, len(all))
	for _, def := range all {
		if def.ExpiryMinutes >= minLiveExpiryMinutes && def.StrikePctOTM <= maxLiveStrikePctOTM {
			if category, ok := optionStrategyCategories[def.Name]; ok {
				def.Category = category
			}
			filtered = append(filtered, def)
		}
	}
	return filtered
}

// BuildNiftyStrategies returns 100 NIFTY 50–native option-selling (theta-decay)
// strategies. These are purpose-built for NIFTY's IV profile (≈ 14-22%) rather
// than BTC-scaled proxies. Wider strikes (0.10-0.20% OTM) and longer expiry
// (120-300 min) provide meaningful premiums at NIFTY's volatility level.
func BuildNiftyStrategies() []StrategyDef {
	return buildNiftyNativeStrategies()
}

// buildAllStrategies defines BTC option SELLING (writing) strategies.
//
// Efficiency Improvements:
//   - All strategies use safer OTM strikes (1.0% - 1.8%) for higher Probability of Profit (POP).
//   - Bullish signals trigger SOLD PUTS.
//   - Bearish signals trigger SOLD CALLS.
//   - TakeProfitPct: 0.36 - 0.52 (bank decay earlier before gamma can reverse it).
//   - StopLossPct: 0.65 - 0.88 (cut premium expansion sooner instead of tolerating doubles).
//   - ExpiryMinutes: 135 - 210 to reduce gamma spikes and keep shorts more stable.
func buildAllStrategies() []StrategyDef {
	return []StrategyDef{

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY A — MOMENTUM CONTINUATION (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "MomentumBurst_Bull_Put_Sell", Type: Put,
			StrikePctOTM: 0.011, ExpiryMinutes: 150,
			TakeProfitPct: 0.38, StopLossPct: 0.70,
			PositionUSD: 10000, Signal: "STRONG_BULL_MOMENTUM", CooldownSecs: 600,
		},
		{
			Name: "MomentumBurst_Bear_Call_Sell", Type: Call,
			StrikePctOTM: 0.011, ExpiryMinutes: 150,
			TakeProfitPct: 0.38, StopLossPct: 0.70,
			PositionUSD: 10000, Signal: "STRONG_BEAR_MOMENTUM", CooldownSecs: 600,
		},
		{
			Name: "ConsecCandle_Bull_Put_Sell", Type: Put,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "CONSEC_BULL_BARS", CooldownSecs: 420,
		},
		{
			Name: "ConsecCandle_Bear_Call_Sell", Type: Call,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "CONSEC_BEAR_BARS", CooldownSecs: 420,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY B — MEAN REVERSION (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "RSIRecovery_Bull_Put_Sell", Type: Put,
			StrikePctOTM: 0.016, ExpiryMinutes: 150,
			TakeProfitPct: 0.42, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "RSI_OVERSOLD_EXTREME", CooldownSecs: 900,
		},
		{
			Name: "RSIFade_Bear_Call_Sell", Type: Call,
			StrikePctOTM: 0.016, ExpiryMinutes: 150,
			TakeProfitPct: 0.42, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "RSI_OVERBOUGHT_EXTREME", CooldownSecs: 900,
		},
		{
			Name: "Overextension_Fade_Call_Sell", Type: Call,
			StrikePctOTM: 0.015, ExpiryMinutes: 180,
			TakeProfitPct: 0.50, StopLossPct: 0.85,
			PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_UP", CooldownSecs: 1200,
		},
		{
			Name: "Overextension_Fade_Put_Sell", Type: Put,
			StrikePctOTM: 0.015, ExpiryMinutes: 180,
			TakeProfitPct: 0.50, StopLossPct: 0.85,
			PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_DOWN", CooldownSecs: 1200,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY C — TECHNICAL BREAKOUT (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "EMA_BullCross_Put_Sell", Type: Put,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "EMA_BULL_CROSS", CooldownSecs: 600,
		},
		{
			Name: "EMA_BearCross_Call_Sell", Type: Call,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "EMA_BEAR_CROSS", CooldownSecs: 600,
		},
		{
			Name: "Resistance_Breakout_Put_Sell", Type: Put,
			StrikePctOTM: 0.011, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "RESISTANCE_BREAK", CooldownSecs: 720,
		},
		{
			Name: "Support_Breakdown_Call_Sell", Type: Call,
			StrikePctOTM: 0.011, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "SUPPORT_BREAK", CooldownSecs: 720,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY D — SPECIAL SITUATIONS (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "Capitulation_VReversal_Put_Sell", Type: Put,
			StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.48, StopLossPct: 0.80,
			PositionUSD: 10000, Signal: "CAPITULATION_RECOVERY", CooldownSecs: 1200,
		},
		{
			Name: "SessionOpen_Bull_Put_Sell", Type: Put,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.36, StopLossPct: 0.65,
			PositionUSD: 10000, Signal: "SESSION_OPEN_BULL", CooldownSecs: 720,
		},
		{
			Name: "SessionOpen_Bear_Call_Sell", Type: Call,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.36, StopLossPct: 0.65,
			PositionUSD: 10000, Signal: "SESSION_OPEN_BEAR", CooldownSecs: 720,
		},
		{
			Name: "VolCompress_Breakout_Bull_Put", Type: Put,
			StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.44, StopLossPct: 0.78,
			PositionUSD: 10000, Signal: "VOL_COMPRESS_BULL", CooldownSecs: 900,
		},
		{
			Name: "VolCompress_Breakout_Bear_Call", Type: Call,
			StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.44, StopLossPct: 0.78,
			PositionUSD: 10000, Signal: "VOL_COMPRESS_BEAR", CooldownSecs: 900,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY E — SELECTIVE ALPHA (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "VWAP_Continuation_Bull_Put", Type: Put,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "VWAP_ABOVE", CooldownSecs: 540,
		},
		{
			Name: "VWAP_Continuation_Bear_Call", Type: Call,
			StrikePctOTM: 0.010, ExpiryMinutes: 135,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "VWAP_BELOW", CooldownSecs: 540,
		},
		{
			Name: "TripleConfluence_Bull_Put", Type: Put,
			StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.74,
			PositionUSD: 10000, Signal: "TRIPLE_BULL", CooldownSecs: 900,
		},
		{
			Name: "TripleConfluence_Bear_Call", Type: Call,
			StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.74,
			PositionUSD: 10000, Signal: "TRIPLE_BEAR", CooldownSecs: 900,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY F — TREND AND STRUCTURE (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "TrendAlignment_Bull_Put", Type: Put,
			StrikePctOTM: 0.010, ExpiryMinutes: 150,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "EMA_ABOVE_BOTH", CooldownSecs: 600,
		},
		{
			Name: "TrendAlignment_Bear_Call", Type: Call,
			StrikePctOTM: 0.010, ExpiryMinutes: 150,
			TakeProfitPct: 0.38, StopLossPct: 0.68,
			PositionUSD: 10000, Signal: "EMA_BELOW_BOTH", CooldownSecs: 600,
		},
		{
			Name: "BBSqueeze_Release_Bull_Put", Type: Put,
			StrikePctOTM: 0.012, ExpiryMinutes: 150,
			TakeProfitPct: 0.42, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "BB_SQUEEZE_BULL", CooldownSecs: 540,
		},
		{
			Name: "BBSqueeze_Release_Bear_Call", Type: Call,
			StrikePctOTM: 0.012, ExpiryMinutes: 150,
			TakeProfitPct: 0.42, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "BB_SQUEEZE_BEAR", CooldownSecs: 540,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// CATEGORY G — HYBRID PRO SERIES (SELLERS)
		// ═══════════════════════════════════════════════════════════════════════

		{
			Name: "MomentumVWAP_Pro_Bull_Put", Type: Put,
			StrikePctOTM: 0.012, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BULL", CooldownSecs: 600,
		},
		{
			Name: "MomentumVWAP_Pro_Bear_Call", Type: Call,
			StrikePctOTM: 0.012, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.72,
			PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BEAR", CooldownSecs: 600,
		},
		{
			Name: "BreakoutTrend_Pro_Bull_Put", Type: Put,
			StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.78,
			PositionUSD: 10000, Signal: "BREAKOUT_TREND_BULL", CooldownSecs: 720,
		},
		{
			Name: "BreakdownTrend_Pro_Bear_Call", Type: Call,
			StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.78,
			PositionUSD: 10000, Signal: "BREAKDOWN_TREND_BEAR", CooldownSecs: 720,
		},
		{
			Name: "Capitulation_Reclaim_Elite_Put", Type: Put,
			StrikePctOTM: 0.018, ExpiryMinutes: 210,
			TakeProfitPct: 0.52, StopLossPct: 0.88,
			PositionUSD: 10000, Signal: "CAPITULATION_RECLAIM", CooldownSecs: 1800,
		},

		// ═══════════════════════════════════════════════════════════════════════
		// IDs 131-154 — NEW SIGNAL COVERAGE
		// ═══════════════════════════════════════════════════════════════════════

		{Name: "BullMom_Quick_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "BULL_MOMENTUM", CooldownSecs: 300},
		{Name: "BearMom_Quick_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "BEAR_MOMENTUM", CooldownSecs: 300},
		{Name: "RSI_Bounce_Bull_Put", Type: Put, StrikePctOTM: 0.014, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.68, PositionUSD: 10000, Signal: "RSI_OVERSOLD", CooldownSecs: 480},
		{Name: "RSI_Fade_Bear_Call", Type: Call, StrikePctOTM: 0.014, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.68, PositionUSD: 10000, Signal: "RSI_OVERBOUGHT", CooldownSecs: 480},
		{Name: "BBLower_Bounce_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "BB_LOWER_TOUCH", CooldownSecs: 360},
		{Name: "BBUpper_Fade_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "BB_UPPER_TOUCH", CooldownSecs: 360},
		{Name: "Stoch_Bounce_Bull_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "STOCH_OVERSOLD", CooldownSecs: 420},
		{Name: "Stoch_Fade_Bear_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "STOCH_OVERBOUGHT", CooldownSecs: 420},
		{Name: "HighIV_Trend_Bull_Put", Type: Put, StrikePctOTM: 0.015, ExpiryMinutes: 150,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "HIGH_IV_BULL", CooldownSecs: 600},
		{Name: "HighIV_Trend_Bear_Call", Type: Call, StrikePctOTM: 0.015, ExpiryMinutes: 150,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "HIGH_IV_BEAR", CooldownSecs: 600},
		{Name: "SharpRev_Bull_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.40, StopLossPct: 0.72, PositionUSD: 10000, Signal: "SHARP_REVERSAL_UP", CooldownSecs: 360},
		{Name: "SharpRev_Bear_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.40, StopLossPct: 0.72, PositionUSD: 10000, Signal: "SHARP_REVERSAL_DOWN", CooldownSecs: 360},
		{Name: "BullMom_Mid_Put", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "BULL_MOMENTUM", CooldownSecs: 480},
		{Name: "BearMom_Mid_Call", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "BEAR_MOMENTUM", CooldownSecs: 480},
		{Name: "BullMom_Wide_Put", Type: Put, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "BULL_MOMENTUM", CooldownSecs: 600},
		{Name: "BearMom_Wide_Call", Type: Call, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "BEAR_MOMENTUM", CooldownSecs: 600},
		{Name: "RSI_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "RSI_OVERSOLD", CooldownSecs: 360},
		{Name: "RSI_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "RSI_OVERBOUGHT", CooldownSecs: 360},
		{Name: "Stoch_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "STOCH_OVERSOLD", CooldownSecs: 300},
		{Name: "Stoch_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "STOCH_OVERBOUGHT", CooldownSecs: 300},
		{Name: "SharpRev_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "SHARP_REVERSAL_UP", CooldownSecs: 540},
		{Name: "SharpRev_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "SHARP_REVERSAL_DOWN", CooldownSecs: 540},
		{Name: "HighIV_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.40, StopLossPct: 0.72, PositionUSD: 10000, Signal: "HIGH_IV_BULL", CooldownSecs: 420},
		{Name: "HighIV_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.40, StopLossPct: 0.72, PositionUSD: 10000, Signal: "HIGH_IV_BEAR", CooldownSecs: 420},

		// ═══════════════════════════════════════════════════════════════════════
		// IDs 155-178 — EMA, BREAKOUT & BB VARIANTS
		// ═══════════════════════════════════════════════════════════════════════

		{Name: "EMABull_Quick_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "EMA_BULL_CROSS", CooldownSecs: 300},
		{Name: "EMABear_Quick_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "EMA_BEAR_CROSS", CooldownSecs: 300},
		{Name: "EMABull_Wide_Put", Type: Put, StrikePctOTM: 0.015, ExpiryMinutes: 180,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "EMA_BULL_CROSS", CooldownSecs: 540},
		{Name: "EMABear_Wide_Call", Type: Call, StrikePctOTM: 0.015, ExpiryMinutes: 180,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "EMA_BEAR_CROSS", CooldownSecs: 540},
		{Name: "EMAAbove_Quick_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "EMA_ABOVE_BOTH", CooldownSecs: 300},
		{Name: "EMABelow_Quick_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "EMA_BELOW_BOTH", CooldownSecs: 300},
		{Name: "EMAAbove_Wide_Put", Type: Put, StrikePctOTM: 0.015, ExpiryMinutes: 165,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "EMA_ABOVE_BOTH", CooldownSecs: 480},
		{Name: "EMABelow_Wide_Call", Type: Call, StrikePctOTM: 0.015, ExpiryMinutes: 165,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "EMA_BELOW_BOTH", CooldownSecs: 480},
		{Name: "ResBrk_Quick_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "RESISTANCE_BREAK", CooldownSecs: 300},
		{Name: "SupBrk_Quick_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "SUPPORT_BREAK", CooldownSecs: 300},
		{Name: "ResBrk_Wide_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "RESISTANCE_BREAK", CooldownSecs: 600},
		{Name: "SupBrk_Wide_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.74, PositionUSD: 10000, Signal: "SUPPORT_BREAK", CooldownSecs: 600},
		{Name: "ResBrk_Mid_Put", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "RESISTANCE_BREAK", CooldownSecs: 480},
		{Name: "SupBrk_Mid_Call", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "SUPPORT_BREAK", CooldownSecs: 480},
		{Name: "BrkTrend_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "BREAKOUT_TREND_BULL", CooldownSecs: 360},
		{Name: "BrkTrend_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "BREAKDOWN_TREND_BEAR", CooldownSecs: 360},
		{Name: "BrkTrend_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.78, PositionUSD: 10000, Signal: "BREAKOUT_TREND_BULL", CooldownSecs: 720},
		{Name: "BrkTrend_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.78, PositionUSD: 10000, Signal: "BREAKDOWN_TREND_BEAR", CooldownSecs: 720},
		{Name: "BBLower_Mid_Put", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "BB_LOWER_TOUCH", CooldownSecs: 480},
		{Name: "BBUpper_Mid_Call", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 150,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "BB_UPPER_TOUCH", CooldownSecs: 480},
		{Name: "BBLower_Wide_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "BB_LOWER_TOUCH", CooldownSecs: 540},
		{Name: "BBUpper_Wide_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "BB_UPPER_TOUCH", CooldownSecs: 540},
		{Name: "BBSqueeze_Quick_Bull", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "BB_SQUEEZE_BULL", CooldownSecs: 300},
		{Name: "BBSqueeze_Quick_Bear", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "BB_SQUEEZE_BEAR", CooldownSecs: 300},

		// ═══════════════════════════════════════════════════════════════════════
		// IDs 179-203 — VWAP, MOMENTUM & CAPITULATION VARIANTS
		// ═══════════════════════════════════════════════════════════════════════

		{Name: "VWAP_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "VWAP_ABOVE", CooldownSecs: 300},
		{Name: "VWAP_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "VWAP_BELOW", CooldownSecs: 300},
		{Name: "VWAP_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.015, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "VWAP_ABOVE", CooldownSecs: 540},
		{Name: "VWAP_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.015, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "VWAP_BELOW", CooldownSecs: 540},
		{Name: "MomVWAP_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BULL", CooldownSecs: 300},
		{Name: "MomVWAP_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BEAR", CooldownSecs: 300},
		{Name: "MomVWAP_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BULL", CooldownSecs: 720},
		{Name: "MomVWAP_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "MOMENTUM_VWAP_BEAR", CooldownSecs: 720},
		{Name: "MomBurst_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "STRONG_BULL_MOMENTUM", CooldownSecs: 300},
		{Name: "MomBurst_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "STRONG_BEAR_MOMENTUM", CooldownSecs: 300},
		{Name: "MomBurst_Mid_Bull_Put", Type: Put, StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "STRONG_BULL_MOMENTUM", CooldownSecs: 480},
		{Name: "MomBurst_Mid_Bear_Call", Type: Call, StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "STRONG_BEAR_MOMENTUM", CooldownSecs: 480},
		{Name: "Consec_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "CONSEC_BULL_BARS", CooldownSecs: 300},
		{Name: "Consec_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.36, StopLossPct: 0.65, PositionUSD: 10000, Signal: "CONSEC_BEAR_BARS", CooldownSecs: 300},
		{Name: "Consec_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "CONSEC_BULL_BARS", CooldownSecs: 480},
		{Name: "Consec_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.014, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "CONSEC_BEAR_BARS", CooldownSecs: 480},
		{Name: "VolComp_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "VOL_COMPRESS_BULL", CooldownSecs: 360},
		{Name: "VolComp_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "VOL_COMPRESS_BEAR", CooldownSecs: 360},
		{Name: "VolComp_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "VOL_COMPRESS_BULL", CooldownSecs: 720},
		{Name: "VolComp_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "VOL_COMPRESS_BEAR", CooldownSecs: 720},
		{Name: "Cap_Quick_Put", Type: Put, StrikePctOTM: 0.014, ExpiryMinutes: 135,
			TakeProfitPct: 0.44, StopLossPct: 0.76, PositionUSD: 10000, Signal: "CAPITULATION_RECOVERY", CooldownSecs: 720},
		{Name: "Cap_Wide_Put", Type: Put, StrikePctOTM: 0.020, ExpiryMinutes: 210,
			TakeProfitPct: 0.50, StopLossPct: 0.84, PositionUSD: 10000, Signal: "CAPITULATION_RECOVERY", CooldownSecs: 1200},
		{Name: "Cap_Reclaim_Quick_Put", Type: Put, StrikePctOTM: 0.014, ExpiryMinutes: 150,
			TakeProfitPct: 0.46, StopLossPct: 0.80, PositionUSD: 10000, Signal: "CAPITULATION_RECLAIM", CooldownSecs: 900},
		{Name: "OverextFade_Quick_Up_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.42, StopLossPct: 0.74, PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_UP", CooldownSecs: 720},
		{Name: "OverextFade_Quick_Down_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.42, StopLossPct: 0.74, PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_DOWN", CooldownSecs: 720},

		// ═══════════════════════════════════════════════════════════════════════
		// IDs 204-230 — TRIPLE, SESSION, RSI EXTREME & REMAINING VARIANTS
		// ═══════════════════════════════════════════════════════════════════════

		{Name: "Triple_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "TRIPLE_BULL", CooldownSecs: 360},
		{Name: "Triple_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "TRIPLE_BEAR", CooldownSecs: 360},
		{Name: "Triple_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.76, PositionUSD: 10000, Signal: "TRIPLE_BULL", CooldownSecs: 900},
		{Name: "Triple_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.76, PositionUSD: 10000, Signal: "TRIPLE_BEAR", CooldownSecs: 900},
		{Name: "Session_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.34, StopLossPct: 0.62, PositionUSD: 10000, Signal: "SESSION_OPEN_BULL", CooldownSecs: 300},
		{Name: "Session_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.009, ExpiryMinutes: 90,
			TakeProfitPct: 0.34, StopLossPct: 0.62, PositionUSD: 10000, Signal: "SESSION_OPEN_BEAR", CooldownSecs: 300},
		{Name: "Session_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "SESSION_OPEN_BULL", CooldownSecs: 720},
		{Name: "Session_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "SESSION_OPEN_BEAR", CooldownSecs: 720},
		{Name: "RSIExtreme_Quick_Bull_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.66, PositionUSD: 10000, Signal: "RSI_OVERSOLD_EXTREME", CooldownSecs: 480},
		{Name: "RSIExtreme_Quick_Bear_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 90,
			TakeProfitPct: 0.38, StopLossPct: 0.66, PositionUSD: 10000, Signal: "RSI_OVERBOUGHT_EXTREME", CooldownSecs: 480},
		{Name: "RSIExtreme_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.74, PositionUSD: 10000, Signal: "RSI_OVERSOLD_EXTREME", CooldownSecs: 900},
		{Name: "RSIExtreme_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.74, PositionUSD: 10000, Signal: "RSI_OVERBOUGHT_EXTREME", CooldownSecs: 900},
		{Name: "Stoch_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "STOCH_OVERSOLD", CooldownSecs: 540},
		{Name: "Stoch_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.016, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "STOCH_OVERBOUGHT", CooldownSecs: 540},
		{Name: "BBSqueeze_Mid_Bull", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "BB_SQUEEZE_BULL", CooldownSecs: 540},
		{Name: "BBSqueeze_Mid_Bear", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 165,
			TakeProfitPct: 0.42, StopLossPct: 0.72, PositionUSD: 10000, Signal: "BB_SQUEEZE_BEAR", CooldownSecs: 540},
		{Name: "HighIV_Wide_Bull_Put", Type: Put, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.78, PositionUSD: 10000, Signal: "HIGH_IV_BULL", CooldownSecs: 720},
		{Name: "HighIV_Wide_Bear_Call", Type: Call, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.46, StopLossPct: 0.78, PositionUSD: 10000, Signal: "HIGH_IV_BEAR", CooldownSecs: 720},
		{Name: "BullMom_Alt_Put", Type: Put, StrikePctOTM: 0.010, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.67, PositionUSD: 10000, Signal: "BULL_MOMENTUM", CooldownSecs: 360},
		{Name: "BearMom_Alt_Call", Type: Call, StrikePctOTM: 0.010, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.67, PositionUSD: 10000, Signal: "BEAR_MOMENTUM", CooldownSecs: 360},
		{Name: "RSI_Mid_Bull_Put", Type: Put, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "RSI_OVERSOLD", CooldownSecs: 420},
		{Name: "RSI_Mid_Bear_Call", Type: Call, StrikePctOTM: 0.012, ExpiryMinutes: 120,
			TakeProfitPct: 0.38, StopLossPct: 0.68, PositionUSD: 10000, Signal: "RSI_OVERBOUGHT", CooldownSecs: 420},
		{Name: "SharpRev_Mid_Bull_Put", Type: Put, StrikePctOTM: 0.013, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "SHARP_REVERSAL_UP", CooldownSecs: 420},
		{Name: "SharpRev_Mid_Bear_Call", Type: Call, StrikePctOTM: 0.013, ExpiryMinutes: 135,
			TakeProfitPct: 0.40, StopLossPct: 0.70, PositionUSD: 10000, Signal: "SHARP_REVERSAL_DOWN", CooldownSecs: 420},
		{Name: "Overext_Wide_Up_Call", Type: Call, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.50, StopLossPct: 0.84, PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_UP", CooldownSecs: 1200},
		{Name: "Overext_Wide_Down_Put", Type: Put, StrikePctOTM: 0.018, ExpiryMinutes: 180,
			TakeProfitPct: 0.50, StopLossPct: 0.84, PositionUSD: 10000, Signal: "OVEREXTENSION_FADE_DOWN", CooldownSecs: 1200},
		{Name: "Cap_Reclaim_Wide_Put", Type: Put, StrikePctOTM: 0.020, ExpiryMinutes: 210,
			TakeProfitPct: 0.54, StopLossPct: 0.90, PositionUSD: 10000, Signal: "CAPITULATION_RECLAIM", CooldownSecs: 1800},
	}
}
