import type { TerminalSnapshot } from "./terminalTypes";

export const initialTerminalSnapshot: TerminalSnapshot = {
  connected: false,
  loading: true,
  price: 0,
  priceChange24hPct: 0,
  spreadBps: 0,
  fundingRate: 0,
  regime: "",
  candles: [],
  bids: [],
  asks: [],
  positions: [],
  risk: {
    var95Usd: 0,
    var99Usd: 0,
    cvar95Usd: 0,
    heatPct: 0,
    drawdownPct: 0,
    netExposureUsd: 0,
    grossExposureUsd: 0,
    marginUsagePct: 0,
    longExposureUsd: 0,
    shortExposureUsd: 0,
    fundingPaidUsd: 0,
    fundingReceivedUsd: 0,
  },
  strategies: [],
  analytics: {
    equityCurve: [],
    rollingSharpe30d: 0,
    rollingSharpe90d: 0,
    profitFactorTrend: 0,
    winRatePct: 0,
    feeDragUsd: 0,
    rMultipleBuckets: [],
  },
  journal: [],
  alerts: [],
  updatedAt: "",
};
