
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "antigravity-engine/internal/risk"


)

var tests = []testing.InternalTest{

	{"TestValidateRejectsOversizedShort", _test.TestValidateRejectsOversizedShort},

	{"TestNotifyFillTracksSignedExposure", _test.TestNotifyFillTracksSignedExposure},

	{"TestStrategyTrackerDisablesAfterThreeConsecutiveLosses", _test.TestStrategyTrackerDisablesAfterThreeConsecutiveLosses},

	{"TestStrategyTrackerDisablesUnderperformingStrategy", _test.TestStrategyTrackerDisablesUnderperformingStrategy},

	{"TestStrategyTrackerSizingMultiplierDefaultsAndUnknown", _test.TestStrategyTrackerSizingMultiplierDefaultsAndUnknown},

	{"TestStrategyTrackerSizingMultiplierBoostsStrongWinners", _test.TestStrategyTrackerSizingMultiplierBoostsStrongWinners},

	{"TestStrategyTrackerSizingMultiplierPenalizesLossStreaksAndDisable", _test.TestStrategyTrackerSizingMultiplierPenalizesLossStreaksAndDisable},

	{"TestStrategyTrackerExecutionWeightDefaults", _test.TestStrategyTrackerExecutionWeightDefaults},

	{"TestStrategyTrackerExecutionWeightBoostsStrongMatureStrategy", _test.TestStrategyTrackerExecutionWeightBoostsStrongMatureStrategy},

	{"TestStrategyTrackerExecutionWeightPenalizesWeakMatureStrategy", _test.TestStrategyTrackerExecutionWeightPenalizesWeakMatureStrategy},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "antigravity-engine"
	testdeps.ImportPath = "antigravity-engine/internal/risk"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

