
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "antigravity-engine/internal/positions"


)

var tests = []testing.InternalTest{

	{"TestLongPartialTakeProfitEmitsEventAndKeepsPositionOpen", _test.TestLongPartialTakeProfitEmitsEventAndKeepsPositionOpen},

	{"TestLongPositionKeepsFixedStopLossAfterProfitMove", _test.TestLongPositionKeepsFixedStopLossAfterProfitMove},

	{"TestOpenPositionReversesLongStopLossAndTakeProfit", _test.TestOpenPositionReversesLongStopLossAndTakeProfit},

	{"TestOpenPositionReversesShortStopLossAndTakeProfit", _test.TestOpenPositionReversesShortStopLossAndTakeProfit},

	{"TestOpenPositionAppliesTakeProfitFloor", _test.TestOpenPositionAppliesTakeProfitFloor},

	{"TestOpenPositionUsesNormalTargetsByDefault", _test.TestOpenPositionUsesNormalTargetsByDefault},

	{"TestCheckExpiredPositionsClosesStalePosition", _test.TestCheckExpiredPositionsClosesStalePosition},

	{"TestCheckExpiredPositionsSkipsYoungPosition", _test.TestCheckExpiredPositionsSkipsYoungPosition},

	{"TestCheckExpiredPositionsDisabledWhenZero", _test.TestCheckExpiredPositionsDisabledWhenZero},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "antigravity-engine"
	testdeps.ImportPath = "antigravity-engine/internal/positions"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

