/**
 * Autonomous browser handoff runner for repo upgrade prompts.
 *
 * Reads the manifest generated by autonomous_repo_bot.py and processes prompt
 * files one by one through a logged-in browser tab for ChatGPT or Claude.
 *
 * Usage:
 *   node autonomous-handoff.js --provider chatgpt
 *   node autonomous-handoff.js --provider claude --limit 2
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const puppeteer = require('puppeteer-core');

const ROOT = path.resolve(__dirname, '..');
const DEFAULT_MANIFEST = path.join(ROOT, 'output', 'autonomous_bot', 'browser_handoff.json');
const OUTPUT_ROOT = path.join(ROOT, 'output', 'autonomous_bot');
const RESULTS_ROOT = path.join(OUTPUT_ROOT, 'browser_results');
const STATUS_FILE = path.join(OUTPUT_ROOT, 'browser_status.json');
const QUEUE_FILE = path.join(OUTPUT_ROOT, 'browser_transport_queue.json');
const RUN_LOG = path.join(__dirname, 'autonomous-handoff.log.jsonl');

const PROVIDERS = {
  chatgpt: {
    label: 'ChatGPT',
    urls: ['https://chatgpt.com/', 'https://chat.openai.com/'],
    urlMatches: ['chatgpt.com', 'chat.openai.com'],
    composerSelectors: [
      '#prompt-textarea',
      'div[contenteditable="true"][id="prompt-textarea"]',
      'textarea[placeholder]',
      'div[contenteditable="true"][data-testid*="composer"]',
      'div[contenteditable="true"][data-testid*="prompt"]',
    ],
    submitSelectors: [
      'button[data-testid="send-button"]',
      'button[aria-label*="Send"]',
      'button[aria-label="Send prompt"]',
    ],
    assistantSelectors: [
      '[data-message-author-role="assistant"]',
      '.markdown.prose',
    ],
    stopSelectors: [
      '[data-testid="stop-button"]',
      'button[aria-label*="Stop"]',
      'button[title*="Stop"]',
      '.result-streaming',
    ],
    loginHints: [
      'log in',
      'sign up',
      'continue with google',
      'continue with microsoft',
      'welcome back',
    ],
    blockedHints: [
      'verify you are human',
      'unusual activity',
      'access denied',
      'captcha',
      'checking if the site connection is secure',
    ],
  },
  claude: {
    label: 'Claude',
    urls: ['https://claude.ai/new', 'https://claude.ai/chats'],
    urlMatches: ['claude.ai'],
    composerSelectors: [
      'div[contenteditable="true"][data-testid="chat-input"]',
      'div[contenteditable="true"].ProseMirror',
      'fieldset div[contenteditable="true"]',
      'div[contenteditable="true"]',
      'textarea',
    ],
    submitSelectors: [
      'button[aria-label*="Send"]',
      'button[data-testid*="send"]',
      'button[type="submit"]',
    ],
    assistantSelectors: [
      '[data-is-streaming]',
      '[data-testid="message-content"]',
      '.font-claude-message',
      'main [class*="prose"]',
    ],
    stopSelectors: [
      'button[aria-label*="Stop"]',
      'button[data-testid*="stop"]',
      '[data-is-streaming="true"]',
    ],
    loginHints: [
      'log in',
      'sign in',
      'continue with google',
      'continue with email',
    ],
    blockedHints: [
      'captcha',
      'verify',
      'blocked',
      'access denied',
    ],
  },
};

const args = parseArgs(process.argv.slice(2));
const provider = PROVIDERS[args.provider];

if (!provider) {
  console.error(`Unknown provider "${args.provider}". Use chatgpt or claude.`);
  process.exit(1);
}

main().catch((error) => {
  logRun({
    stage: 'fatal',
    provider: args.provider,
    error: error.message,
  });
  if (String(error.message || '').includes('webSocket URL') || String(error.message || '').includes('ECONNREFUSED')) {
    console.error('Chrome is not reachable on the remote debugging port.');
    console.error('Start Chrome with: chrome.exe --remote-debugging-port=9222');
    console.error(`Then log into ${provider.label} and rerun the handoff command.`);
  }
  console.error(error);
  process.exit(1);
});

async function main() {
  ensureDir(RESULTS_ROOT);

  const manifest = readJson(args.manifest);
  const promptFiles = Array.isArray(manifest.prompt_files) ? manifest.prompt_files : [];
  const selected = args.limit > 0 ? promptFiles.slice(0, args.limit) : promptFiles;
  const queue = loadQueue();
  const queueItems = syncQueueItems(queue, manifest, selected, args.provider);
  const runnableItems = args.force
    ? queueItems
    : queueItems.filter((item) => !item.next_retry_at || new Date(item.next_retry_at).getTime() <= Date.now());

  if (runnableItems.length === 0) {
    console.log('No prompt files found in manifest.');
    writeQueue(queue);
    return;
  }

  console.log(`Starting autonomous handoff for ${provider.label}`);
  console.log(`Manifest: ${args.manifest}`);
  console.log(`Prompt count: ${runnableItems.length}`);

  const browser = await puppeteer.connect({
    browserURL: args.browserUrl,
    defaultViewport: null,
  });

  try {
    const page = await getProviderPage(browser, provider);
    await ensureProviderReady(page, provider);

    const status = readStatus();
    status.last_run = new Date().toISOString();
    status.provider = args.provider;
    status.manifest = path.relative(ROOT, args.manifest);
    status.prompts = status.prompts || {};
    writeStatus(status);

    for (const item of runnableItems) {
      const relativePromptFile = item.prompt_file;
      const promptPath = path.resolve(ROOT, relativePromptFile);
      if (!fs.existsSync(promptPath)) {
        markQueueItem(queue, item.id, {
          status: 'error',
          last_error: 'prompt file missing',
          last_error_class: 'prompt_missing',
        });
        updatePromptStatus(status, relativePromptFile, {
          state: 'error',
          error: 'prompt file missing',
        });
        continue;
      }

      if (!args.force && isPromptComplete(status, relativePromptFile, args.provider)) {
        console.log(`Skipping completed prompt: ${relativePromptFile}`);
        continue;
      }

      console.log(`Processing: ${relativePromptFile}`);
      updatePromptStatus(status, relativePromptFile, {
        state: 'running',
        provider: args.provider,
        started_at: new Date().toISOString(),
      });
      markQueueItem(queue, item.id, {
        status: 'running',
        last_attempt_at: new Date().toISOString(),
        attempt_count: Number(item.attempt_count || 0) + 1,
        provider: args.provider,
      });

      try {
        if (args.newChatEachPrompt) {
          await openFreshChat(page, provider);
        }
        const promptText = fs.readFileSync(promptPath, 'utf8');
        const previousReply = await readLastAssistantMessage(page, provider);
        await submitPrompt(page, provider, promptText);
        const responseText = await waitForAssistantResponse(page, provider, previousReply);
        const saved = saveResponse(args.provider, relativePromptFile, promptText, responseText);

        updatePromptStatus(status, relativePromptFile, {
          state: 'completed',
          provider: args.provider,
          completed_at: new Date().toISOString(),
          response_file: path.relative(ROOT, saved.responsePath),
          prompt_copy_file: path.relative(ROOT, saved.promptCopyPath),
        });
        markQueueItem(queue, item.id, {
          status: 'completed',
          completed_at: new Date().toISOString(),
          response_file: path.relative(ROOT, saved.responsePath),
          prompt_copy_file: path.relative(ROOT, saved.promptCopyPath),
          last_error: '',
          last_error_class: '',
          next_retry_at: '',
        });

        logRun({
          stage: 'prompt_completed',
          queue_id: item.id,
          provider: args.provider,
          prompt_file: relativePromptFile,
          response_file: path.relative(ROOT, saved.responsePath),
        });
      } catch (error) {
        const errorClass = classifyError(error);
        const nextRetryAt = new Date(Date.now() + retryDelayMs(Number(item.attempt_count || 0))).toISOString();
        updatePromptStatus(status, relativePromptFile, {
          state: 'error',
          provider: args.provider,
          failed_at: new Date().toISOString(),
          error: error.message,
        });
        markQueueItem(queue, item.id, {
          status: 'error',
          failed_at: new Date().toISOString(),
          last_error: error.message,
          last_error_class: errorClass,
          next_retry_at: nextRetryAt,
        });

        logRun({
          stage: 'prompt_error',
          queue_id: item.id,
          provider: args.provider,
          prompt_file: relativePromptFile,
          error_class: errorClass,
          error: error.message,
        });

        if (!args.continueOnError) {
          throw error;
        }
      }
    }

    console.log('Autonomous handoff complete.');
  } finally {
    writeQueue(queue);
    await browser.disconnect();
  }
}

function parseArgs(argv) {
  const parsed = {
    provider: 'chatgpt',
    manifest: DEFAULT_MANIFEST,
    browserUrl: 'http://localhost:9222',
    limit: 0,
    force: false,
    continueOnError: false,
    newChatEachPrompt: true,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const value = argv[i];
    if (value === '--provider' && argv[i + 1]) {
      parsed.provider = argv[++i];
    } else if (value === '--manifest' && argv[i + 1]) {
      parsed.manifest = path.resolve(argv[++i]);
    } else if (value === '--browser-url' && argv[i + 1]) {
      parsed.browserUrl = argv[++i];
    } else if (value === '--limit' && argv[i + 1]) {
      parsed.limit = Number(argv[++i]) || 0;
    } else if (value === '--force') {
      parsed.force = true;
    } else if (value === '--continue-on-error') {
      parsed.continueOnError = true;
    } else if (value === '--reuse-chat') {
      parsed.newChatEachPrompt = false;
    }
  }

  return parsed;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function readStatus() {
  if (!fs.existsSync(STATUS_FILE)) {
    return {
      created_at: new Date().toISOString(),
      prompts: {},
    };
  }
  return readJson(STATUS_FILE);
}

function writeStatus(status) {
  fs.writeFileSync(STATUS_FILE, JSON.stringify(status, null, 2));
}

function loadQueue() {
  if (!fs.existsSync(QUEUE_FILE)) {
    return {
      created_at: new Date().toISOString(),
      items: [],
    };
  }
  return readJson(QUEUE_FILE);
}

function writeQueue(queue) {
  fs.writeFileSync(QUEUE_FILE, JSON.stringify(queue, null, 2));
}

function syncQueueItems(queue, manifest, promptFiles, providerName) {
  queue.manifest = path.relative(ROOT, args.manifest);
  queue.provider = providerName;
  queue.updated_at = new Date().toISOString();
  queue.items = queue.items || [];

  for (const promptFile of promptFiles) {
    const id = buildQueueId(providerName, promptFile);
    const existing = queue.items.find((item) => item.id === id);
    if (existing) {
      existing.prompt_file = promptFile;
      existing.provider = providerName;
      existing.manifest = path.relative(ROOT, args.manifest);
      continue;
    }
    queue.items.push({
      id,
      prompt_file: promptFile,
      provider: providerName,
      manifest: path.relative(ROOT, args.manifest),
      status: 'pending',
      attempt_count: 0,
      next_retry_at: '',
    });
  }

  writeQueue(queue);
  return queue.items
    .filter((item) => item.provider === providerName && promptFiles.includes(item.prompt_file))
    .sort((a, b) => a.prompt_file.localeCompare(b.prompt_file));
}

function buildQueueId(providerName, promptFile) {
  return crypto.createHash('sha1').update(`${providerName}:${promptFile}`).digest('hex').slice(0, 12);
}

function markQueueItem(queue, id, patch) {
  const item = queue.items.find((entry) => entry.id === id);
  if (!item) {
    return;
  }
  Object.assign(item, patch);
  queue.updated_at = new Date().toISOString();
  writeQueue(queue);
}

function updatePromptStatus(status, promptFile, patch) {
  status.prompts[promptFile] = {
    ...(status.prompts[promptFile] || {}),
    ...patch,
  };
  writeStatus(status);
}

function isPromptComplete(status, promptFile, providerName) {
  const entry = status.prompts[promptFile];
  return entry && entry.state === 'completed' && entry.provider === providerName;
}

function classifyError(error) {
  const message = String(error && error.message ? error.message : error);
  if (message.includes('Timed out waiting')) {
    return 'timeout';
  }
  if (message.includes('composer not found') || message.includes('Failed to submit prompt')) {
    return 'submit_failed';
  }
  if (message.includes('login is required')) {
    return 'login_required';
  }
  if (message.includes('blocked') || message.includes('verification')) {
    return 'blocked';
  }
  if (message.includes('webSocket URL') || message.includes('ECONNREFUSED')) {
    return 'browser_unreachable';
  }
  if (message.includes('prompt file missing')) {
    return 'prompt_missing';
  }
  return 'unknown';
}

function retryDelayMs(attemptCount) {
  const clamped = Math.max(1, attemptCount + 1);
  return Math.min(15 * 60 * 1000, 30 * 1000 * Math.pow(2, clamped - 1));
}

function logRun(entry) {
  fs.appendFileSync(
    RUN_LOG,
    JSON.stringify({
      ts: new Date().toISOString(),
      ...entry,
    }) + '\n',
    'utf8'
  );
}

async function getProviderPage(browser, config) {
  const pages = await browser.pages();
  for (const page of pages) {
    const url = page.url();
    if (config.urlMatches.some((match) => url.includes(match))) {
      return page;
    }
  }

  const page = await browser.newPage();
  await page.goto(config.urls[0], { waitUntil: 'domcontentloaded' });
  return page;
}

async function ensureProviderReady(page, config) {
  await page.bringToFront();
  const start = Date.now();

  while (Date.now() - start < 30000) {
    const state = await inspectProviderState(page, config);
    if (state.blocked) {
      throw new Error(`${config.label} is blocked or verification is required at ${state.url}`);
    }
    if (state.loginRequired) {
      throw new Error(`${config.label} login is required at ${state.url}`);
    }
    if (state.hasComposer) {
      return;
    }
    await delay(1000);
  }

  throw new Error(`${config.label} prompt composer was not found`);
}

async function openFreshChat(page, config) {
  const target = config.urls[0];
  await page.goto(target, { waitUntil: 'domcontentloaded' });
  await delay(1500);
  await ensureProviderReady(page, config);
}

async function inspectProviderState(page, config) {
  return page.evaluate((providerConfig) => {
    const text = document.body ? (document.body.innerText || '').toLowerCase() : '';
    const hasComposer = providerConfig.composerSelectors.some((selector) => document.querySelector(selector));
    const loginRequired = !hasComposer && providerConfig.loginHints.some((hint) => text.includes(hint));
    const blocked = providerConfig.blockedHints.some((hint) => text.includes(hint));

    return {
      hasComposer,
      loginRequired,
      blocked,
      url: window.location.href,
      title: document.title || '',
    };
  }, config);
}

async function readLastAssistantMessage(page, config) {
  return page.evaluate((providerConfig) => {
    for (const selector of providerConfig.assistantSelectors) {
      const nodes = Array.from(document.querySelectorAll(selector));
      if (nodes.length > 0) {
        const last = nodes[nodes.length - 1];
        const text = last.innerText || last.textContent || '';
        if (text.trim()) {
          return text;
        }
      }
    }
    return '';
  }, config);
}

async function submitPrompt(page, config, promptText) {
  let lastState = null;

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    await ensureProviderReady(page, config);
    await fillComposer(page, config, promptText);
    await delay(500);

    lastState = await getComposerState(page, config);
    if (!lastState.found) {
      throw new Error(`${config.label} composer not found`);
    }
    if (!lastState.text.trim()) {
      continue;
    }

    await page.keyboard.press('Enter');
    await delay(800);

    lastState = await getComposerState(page, config);
    if (!lastState.text.trim()) {
      return;
    }

    const clicked = await clickSubmitButton(page, config);
    if (clicked) {
      await delay(800);
      lastState = await getComposerState(page, config);
      if (!lastState.text.trim()) {
        return;
      }
    }

    await page.keyboard.down('Control');
    await page.keyboard.press('Enter');
    await page.keyboard.up('Control');
    await delay(800);

    lastState = await getComposerState(page, config);
    if (!lastState.text.trim()) {
      return;
    }
  }

  const extra = lastState
    ? `textLength=${lastState.text.trim().length} sendButtonEnabled=${lastState.sendButtonEnabled}`
    : 'composerState=unavailable';
  throw new Error(`Failed to submit prompt to ${config.label} (${extra})`);
}

async function fillComposer(page, config, promptText) {
  const inserted = await page.evaluate((providerConfig, text) => {
    let composer = null;
    for (const selector of providerConfig.composerSelectors) {
      const candidate = document.querySelector(selector);
      if (candidate) {
        composer = candidate;
        break;
      }
    }

    if (!composer) {
      return false;
    }

    composer.focus();

    if ('value' in composer) {
      composer.value = '';
      composer.dispatchEvent(new Event('input', { bubbles: true }));
      composer.value = text;
      composer.dispatchEvent(new Event('input', { bubbles: true }));
      composer.dispatchEvent(new Event('change', { bubbles: true }));
      return true;
    }

    composer.textContent = '';
    composer.dispatchEvent(new InputEvent('input', {
      bubbles: true,
      inputType: 'deleteContentBackward',
      data: null,
    }));
    composer.textContent = text;
    composer.dispatchEvent(new InputEvent('input', {
      bubbles: true,
      inputType: 'insertText',
      data: text,
    }));
    return true;
  }, config, promptText);

  if (!inserted) {
    throw new Error(`${config.label} composer not found`);
  }
}

async function getComposerState(page, config) {
  return page.evaluate((providerConfig) => {
    let composer = null;
    for (const selector of providerConfig.composerSelectors) {
      const candidate = document.querySelector(selector);
      if (candidate) {
        composer = candidate;
        break;
      }
    }

    let sendButtonEnabled = false;
    for (const selector of providerConfig.submitSelectors) {
      const button = document.querySelector(selector);
      if (button instanceof HTMLButtonElement && !button.disabled) {
        sendButtonEnabled = true;
        break;
      }
    }

    if (!composer) {
      return {
        found: false,
        text: '',
        sendButtonEnabled,
      };
    }

    const text = 'value' in composer
      ? String(composer.value || '')
      : String(composer.innerText || composer.textContent || '');

    return {
      found: true,
      text,
      sendButtonEnabled,
    };
  }, config);
}

async function clickSubmitButton(page, config) {
  return page.evaluate((providerConfig) => {
    for (const selector of providerConfig.submitSelectors) {
      const button = document.querySelector(selector);
      if (button instanceof HTMLButtonElement && !button.disabled) {
        button.click();
        return true;
      }
    }
    return false;
  }, config);
}

async function waitForAssistantResponse(page, config, previousText) {
  const start = Date.now();
  let lastText = previousText;
  let stableSince = 0;

  while (Date.now() - start < 180000) {
    const streaming = await page.evaluate((providerConfig) => {
      return providerConfig.stopSelectors.some((selector) => document.querySelector(selector));
    }, config);

    const currentText = (await readLastAssistantMessage(page, config)).trim();
    const hasNewText = currentText && currentText !== previousText;

    if (hasNewText && !streaming) {
      if (currentText !== lastText) {
        lastText = currentText;
        stableSince = Date.now();
      } else if (stableSince && Date.now() - stableSince >= 2500) {
        return currentText;
      }
    } else {
      if (currentText !== lastText) {
        lastText = currentText;
      }
      stableSince = 0;
    }

    await delay(800);
  }

  throw new Error(`Timed out waiting for ${config.label} response`);
}

function saveResponse(providerName, relativePromptFile, promptText, responseText) {
  const providerDir = path.join(RESULTS_ROOT, providerName);
  ensureDir(providerDir);

  const stem = path.basename(relativePromptFile, path.extname(relativePromptFile));
  const safeStem = stem.replace(/[^a-zA-Z0-9._-]+/g, '_');
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const base = `${timestamp}_${safeStem}`;

  const promptCopyPath = path.join(providerDir, `${base}.prompt.md`);
  const responsePath = path.join(providerDir, `${base}.response.md`);
  const metaPath = path.join(providerDir, `${base}.json`);

  fs.writeFileSync(promptCopyPath, promptText, 'utf8');
  fs.writeFileSync(responsePath, responseText, 'utf8');
  fs.writeFileSync(metaPath, JSON.stringify({
    provider: providerName,
    prompt_file: relativePromptFile,
    prompt_copy_file: path.relative(ROOT, promptCopyPath),
    response_file: path.relative(ROOT, responsePath),
    saved_at: new Date().toISOString(),
  }, null, 2));

  return { promptCopyPath, responsePath, metaPath };
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
