"use client";

import type { MockRejectionEvent, MockTradingDiagnostics } from "../trading/mockTradingEngine";

/**
 * Diagnostics Root Cause Engine
 * Analyzes rejections to explain why no trades are occurring.
 */

export interface RootCauseAnalysis {
  primaryReason: string;
  recommendation: string;
  severity: "LOW" | "MEDIUM" | "HIGH";
}

export function analyzeRootCause(diagnostics: MockTradingDiagnostics): RootCauseAnalysis {
  const { rejectionCounts, funnel } = diagnostics;

  if (funnel.signalsGenerated === 0) {
    return {
      primaryReason: "No signals generated by strategies.",
      recommendation: "Check strategy logic or market volatility. Strategies may be too restrictive.",
      severity: "HIGH",
    };
  }

  if (funnel.tradesCreated === 0) {
    // Find the biggest bottleneck in the funnel
    const stages = [
      { name: "Confidence", count: funnel.confidencePassed },
      { name: "Score", count: funnel.scorePassed },
      { name: "Risk/Reward", count: funnel.riskRewardPassed },
      { name: "Risk", count: funnel.riskPassed },
      { name: "Cooldown", count: funnel.cooldownPassed },
      { name: "Exposure", count: funnel.exposurePassed },
    ];

    let bottleneck = stages[0];
    for (let i = 1; i < stages.length; i++) {
      if (stages[i].count < bottleneck.count) {
        bottleneck = stages[i];
      }
    }

    if (rejectionCounts.DAILY_LOSS_LIMIT > 0) {
      return {
        primaryReason: "Daily loss limit reached.",
        recommendation: "Wait for the next 24h window or adjust dailyLossLimitPct in config.",
        severity: "MEDIUM",
      };
    }

    if (rejectionCounts.MAX_DRAWDOWN > 0) {
      return {
        primaryReason: "Maximum drawdown limit breached.",
        recommendation: "Review strategy performance or increase maxDrawdownPct if appropriate.",
        severity: "HIGH",
      };
    }

    if (rejectionCounts.EXPOSURE_LIMIT > 0) {
      return {
        primaryReason: "Portfolio exposure limit reached.",
        recommendation: "Wait for existing trades to close or increase maxOpenMockTrades.",
        severity: "MEDIUM",
      };
    }

    return {
      primaryReason: `Bottleneck detected at ${bottleneck.name} stage.`,
      recommendation: `Only ${bottleneck.count} signals passed the ${bottleneck.name} check. Review related parameters.`,
      severity: "MEDIUM",
    };
  }

  return {
    primaryReason: "System operating normally.",
    recommendation: "No immediate action required.",
    severity: "LOW",
  };
}
