
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "antigravity-engine/internal/strategy"


)

var tests = []testing.InternalTest{

	{"TestBuildCuratedScalpersHasUniqueNamesAndExpectedCount", _test.TestBuildCuratedScalpersHasUniqueNamesAndExpectedCount},

	{"TestNormalizeCategoryForIntradayFamilies", _test.TestNormalizeCategoryForIntradayFamilies},

	{"TestGroupByTimeframeIncludes15mBucket", _test.TestGroupByTimeframeIncludes15mBucket},

	{"TestVWAPRSI2ReversionScalperSignalsLong", _test.TestVWAPRSI2ReversionScalperSignalsLong},

	{"TestATRVolumeImpulseScalperRejectsOverextendedBreakout", _test.TestATRVolumeImpulseScalperRejectsOverextendedBreakout},

	{"TestMACDVWAPFlipScalperWaitsForFreshHistogramFlip", _test.TestMACDVWAPFlipScalperWaitsForFreshHistogramFlip},

	{"TestOpeningRangeBreakoutScalperSignalsLong", _test.TestOpeningRangeBreakoutScalperSignalsLong},

	{"TestChartWedgeBreakoutScalperSignalsLong", _test.TestChartWedgeBreakoutScalperSignalsLong},

	{"TestChartDoubleTapReversalScalperSignalsLong", _test.TestChartDoubleTapReversalScalperSignalsLong},

	{"TestSentimentConfluenceProScalperSignalsLong", _test.TestSentimentConfluenceProScalperSignalsLong},

	{"TestSentimentConfluenceProScalperSignalsShort", _test.TestSentimentConfluenceProScalperSignalsShort},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "antigravity-engine"
	testdeps.ImportPath = "antigravity-engine/internal/strategy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

