package scalpers

// buildImmortalEditionPack returns S80-S99 — the "IMMORTAL EDITION" 20-strategy
// research-backed pack. All strategies are registered LIVE immediately without
// any withRolloutPhase() wrapper. withShadowOverride() is applied uniformly
// by BuildCuratedScalpers() after this function returns.
func buildImmortalEditionPack() []RegistryEntry {
	return []RegistryEntry{
		{
			Strategy:     &ElderTripleScreen{},
			Name:         "Elder_Triple_Screen",
			Description:  "S80: Alexander Elder 3-screen system — 4h EMA slope trend, 1h RSI pullback oscillator, 15m entry candle. Elder 'Trading For A Living' (1993).",
			Regimes:      []Regime{RegimeTrending},
			Timeframes:   []string{"15m", "1h", "4h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &CoppockCurveMomentum{},
			Name:         "Coppock_Curve_Momentum",
			Description:  "S81: Edwin Coppock 1962 WMA(ROC14+ROC11,10) momentum oscillator on 4h. Cross from negative to positive = LONG.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging},
			Timeframes:   []string{"4h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &ChandeMomentumOscillator{},
			Name:         "Chande_Momentum_Oscillator",
			Description:  "S82: Tushar Chande CMO (1994) raw sum-of-gains vs losses, range -100..+100. Cross above +50 or below -50 with vol surge on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &KnowSureThingMomentum{},
			Name:         "Know_Sure_Thing_Momentum",
			Description:  "S83: Martin Pring KST (1993) composite weighted ROC across 4 periods. KST/signal cross with 1h EMA trend confirmation.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &AroonTrendConfirmation{},
			Name:         "Aroon_Trend_Confirmation",
			Description:  "S84: Tushar Chande Aroon (1995) — bars-since-high/low ratio. Aroon Up>70 + Down<30 for 2+ bars = strong uptrend entry on 1h.",
			Regimes:      []Regime{RegimeTrending},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &NR7VolatilityCompression{},
			Name:         "NR7_Volatility_Compression",
			Description:  "S85: Toby Crabel NR7 (1990) — current range narrower than prior 7 bars predicts volatility expansion. Breakout entry on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &VolatilityRatioBreakout{},
			Name:         "Volatility_Ratio_Breakout",
			Description:  "S86: Schwager (1996) volatility ratio — ATR/avgATR < 0.5 for 3+ bars then 20-bar range breakout with increasing volume on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &InsideBarMomentum{},
			Name:         "Inside_Bar_Momentum",
			Description:  "S87: Nison (1991) inside bar (harami) indecision pattern. Breakout above/below mother bar on 1h with ADX>15 and volume surge.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &SqueezeMomentumBreakout{},
			Name:         "Squeeze_Momentum_Breakout",
			Description:  "S88: John Carter squeeze (2006) — BB inside Keltner Channel for 3+ bars then expansion fires. Momentum sign = direction on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &HistoricalVolPercentileBreakout{},
			Name:         "Historical_Vol_Percentile_Breakout",
			Description:  "S89: Sinclair (2008) vol percentile — 1h BB width in bottom 20th percentile then 15m 10-bar range breakout = vol expansion entry.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m", "1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &ThreeBarReversal{},
			Name:         "Three_Bar_Reversal",
			Description:  "S90: Bulkowski (2000) three-bar exhaustion reversal — two consecutive same-direction bars then reversal close, RSI extreme on 15m.",
			Regimes:      []Regime{RegimeRanging},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &TrendContinuationPullback{},
			Name:         "Trend_Continuation_Pullback",
			Description:  "S91: Carney (2010) AB=CD harmonic pattern — identify >1.5% leg on 1h, pull back to 50-62% Fibonacci, resume with CVD confirmation.",
			Regimes:      []Regime{RegimeTrending},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &EngulfingBarReversal{},
			Name:         "Engulfing_Bar_Reversal",
			Description:  "S92: Nison (1991) / Marshall et al. (2006) engulfing pattern at swing levels. Body engulf + RSI extreme + CVD confirmation on 15m.",
			Regimes:      []Regime{RegimeRanging, RegimeTrending},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &PinBarReversal{},
			Name:         "Pin_Bar_Reversal",
			Description:  "S93: Nison (1991) hammer/shooting star. Wick >2.5x body at swing level, volume >1.5x avg, CVD opposing wick direction on 15m.",
			Regimes:      []Regime{RegimeRanging, RegimeTrending},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &MorningEveningStar{},
			Name:         "Morning_Evening_Star",
			Description:  "S94: Nison (1991) / Bulkowski (2000) 3-candle star patterns at swing levels. Third bar volume confirmation on 1h.",
			Regimes:      []Regime{RegimeRanging, RegimeTrending},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &VolumePOCMagnet{},
			Name:         "Volume_Profile_POC_Magnet",
			Description:  "S95: Steidlmayer Market Profile (1986) Point of Control magnet. Price >1% from 48-bar POC with fading momentum → trade toward POC.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m", "1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &OBVDivergence{},
			Name:         "OBV_Divergence",
			Description:  "S96: Granville OBV (1963) price-volume divergence. New 20-bar price extreme without OBV confirmation over 3+ bars = reversal signal on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
		{
			Strategy:     &ChaikinMoneyFlowSignal{},
			Name:         "Chaikin_Money_Flow_Signal",
			Description:  "S97: Chaikin CMF (1980s) — MFV-weighted volume flow. CMF crosses ±0.05 threshold aligned with EMA20 price position on 1h.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &MultiIndicatorConsensus{},
			Name:         "Multi_Indicator_Consensus",
			Description:  "S98: Ensemble rule-based system (Krauss et al. 2017). 8 independent binary signals — 6/8 agree=0.68 conf, 7/8=0.74, 8/8=0.80. Fires rarely but with high accuracy.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m", "1h"},
			MaxPositions: 1,
		},
		{
			Strategy:     &AdaptiveTrendFollowing{},
			Name:         "Adaptive_Trend_Following",
			Description:  "S99: Kaufman ER-based adaptive system (1995/2001). ER>0.6=breakout, ER 0.3-0.6=CVD-confirmed, ER<0.3=NoSignal. KAMA-filtered Donchian entry on 15m.",
			Regimes:      []Regime{RegimeTrending, RegimeRanging, RegimeVolatile},
			Timeframes:   []string{"15m"},
			MaxPositions: 1,
		},
	}
}
